### ISSUE TITLE
To parallelize data table execution

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#496] opened 2016-08-03 08:34 UTC
Created from the feedback received on getgauge/gauge#493
Run steps in a single spec, parallelly; providing a table at the setup. In that way I could save execution time for different inputs red from the csv table.

**Comment by apoorvam** [comment] 2016-08-25 05:59
This is duplicate of #306. Closing this for now.

**Closed by apoorvam** 2016-08-25 05:59 UTC
Labels: enhancement
