### ISSUE TITLE
How to get updated CSV data for multiple environment support

### ISSUE THREAD

**Issue by vinodbhardwaj1** [getgauge/gauge#1334] opened 2019-02-06 09:49 UTC
In continuation of issue "**is it possible to have data per environment? how can this be done? #586**"; I need to supply different csv file based on environment.
I'm calling a method in **BeforeSuite** hook which copies my test data from specific env folder to execution env folder.  [means I updated the csv file before consuming in scenario]

But during execution; my step is still referring the old csv data.

Kindly assist.

### Expected behavior
In scenario execution; updated csv should be called.
table:src/test/resources/testdata/execution/data.csv

### Actual behavior
Old csv file is referring.

### Steps to reproduce
table:src/test/resources/testdata/execution/data.csv
Login
----------------
* User Login into application with <USER_EMAIL_ID>,<PASSWORD>

### Gauge version
Gauge version: 1.0.3

Plugins
-------
html-report (4.0.6)
java (0.6.9)
screenshot (0.0.1)
```

**Comment by nehashri** [comment] 2019-02-06 09:58
duplicate of https://github.com/getgauge/gauge/issues/1083

**Closed** 2019-02-06 10:32 UTC
Labels: community
