### ISSUE TITLE
Ability to pin plugin versions in manifest.json

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1656] opened 2020-05-30 21:38 UTC
### Description
By default, when running gauge it would install latest versions of the plugins automatically in background.

This results in unpredictable versions when there are newer versions of plugins. 

It would be great, if we could pin the versions in manifest per plugin so we can have more predictable builds across multiple runs and systems. 

### What command(s) did you run when you found the bug?

For e.g. 
```
gauge run specs
```

#### Gauge (Output of `gauge -v`)

All
#### Operating System information
All

**Comment by sriv** [comment] 2020-06-04 14:32
@haroon-sheikh - thanks for the idea - curious to know what issues you see with plugin upgrades?

From the initial days, we've stayed away from pinning plugin versions and instead focused on backward compatibility.

For the rare cases where backward compatibility had to be sacrificed, gauge/plugin use a version range. ex: https://github.com/getgauge/gauge-java/blob/master/java.json#L40 marks gauge-java `0.7.8` to work with minimum version `1.0.7` of gauge.

**Comment by haroon-sheikh** [comment] 2020-06-04 15:16
This is one of the problems:

```sh
Installed version of gauge-java(0.7.8) does not match with dependency gauge-java(0.7.6) specified in pom.xml file
```

**Comment by sriv** [comment] 2020-06-05 04:46
That is something we included, to let users know that because `gauge install java` would install the latest of `gauge-java` but it wouldn't update `pom.xml` or `build.gradle`.

On a related note, I think 

- version pinning would be a global feature, rolling it into all language runners. 
- every language ecosystem has it's own dependency management, and this would add another layer on top. 

### an alternative

I believe most of the problem stem from the fact that `gauge-java` is a fat jar, containing the types required for authoring, and the runtime required for execution. This has some effect:

- when running via maven/gradle, hence maven/gradle manage the dependency. It so happens that with gauge checks the plugins directory and figures it has gauge-java (say, `0.7.8`) and tries to communicate accordingly. But maven/gradle load the version mentioned in the project, so it could load `0.7.4`, and this causes the runtime incompatibility

- any project that includes `gauge-java` as a dependency inherits it's transitive dependency. This is unnecessary, and can lead to
   -  version conflict
   - longer build times!

I think one way out of this (and cleaner IMO) is to separate gauge-types and gauge-runtime. `gauge-types` would contain `Step` , `*Hook`, ScreenshotGrabber etc.

/cc @getgauge/core @zabil

**Comment by zabil** [comment] 2020-07-20 13:04
Version pinning is a reasonable mechanism adopted in ruby and node ecosystems as they depend on a lot of external packages which in turn have their dependency graph. 

However, Gauge and its plugins does not have many third party dependencies. There's has been a lot of issues with the recent upgrades as new versions of Gauge and it's plugin moved to using gprc, changed how reports are generated for cleaner code base and performance. Now that the migration is complete there will hopefully be no more breaking changes that will require version pinning. 

I am closing this issue for now, but please feel free to discuss this further. Will re-open if this is required after the next few releases.

**Closed by zabil** 2020-07-20 13:04 UTC

**Comment by FaustXVI** [comment] 2024-06-12 08:30
I ended up having this issue today because `gauge-ts` updated and ask for node 20 and my CI (github action) is with node 18. I could just update my node but not being able to pin a plugin version make the build not so reproducible (which is an issue for me in principle and for legal reasons).

Lucky for me, I found a workaround : 
I download the plugin version I want as a zip and install it with `gauge install my-plugin-name -f /path/to/zip/file`
I put that in a script that I run at the same time as I install gauge (npm in my case)
