### ISSUE TITLE
Gauge is not taking screenshot when specs folder has child folders

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1605] opened 2020-03-16 00:10 UTC
Gauge is not taking screenshot when specification files are saved inside specs\child folder

1. Create a new project using "gauge init dotnet"
2. Go to specs folder and create a new folder "Examples"
3. Move example.spec file from specs to newly created Examples folder
4. Open StepImplementation.cs file and add "GaugeScreenshots.Capture()" in method SetLanguageVowels
5. Run command "gauge run specs" or "gauge run specs/Examples"
6. Screenshots are missing

Screenshots attached
[screenshots.docx](https://github.com/getgauge/gauge/files/4335518/screenshots.docx)

Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
dotnet (0.1.3)
html-report (4.0.9)
json-report (0.3.2)
screenshot (0.0.1)
xml-report (0.2.3)

**Comment by sriv** [comment] 2020-03-16 06:09
possibly duplicate of https://github.com/getgauge/html-report/issues/251 which was fixed by getgauge/html-report#253. You'll have to install html-report from source to try this out.

**Comment by manavghaigithub** [comment] 2020-03-17 14:53
@sriv when is the new version of html going to be available? If it is going to be in next few day then i dont mind waiting.

**Comment by sriv** [comment] 2020-03-19 02:14
There isn't a date yet, but we'll try to make a release soon.

**Comment by manavghaigithub** [comment] 2020-03-31 16:56
@sriv Dont mean to bother you but just want to understand if there is any update on the new version of HTML. please advise.

**Comment by sriv** [comment] 2020-03-31 17:06
Sorry! I wanted to post back here, but it slipped my mind. Please update html-report to 4.0.10 (https://github.com/getgauge/html-report/releases/tag/v4.0.10) - it should contain this fix.

Marking this as closed, please feel free to comment if there's anything further on this.

**Closed by sriv** 2020-03-31 17:06 UTC
