### ISSUE TITLE
 json logger does not capture stdout and send it back

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#861] opened 2017-11-15 11:08 UTC
**Expected behavior**
On Visual studio, I should be able to see the output when the tests pass.

**Actual behavior**
<img width="150" alt="nooutput" src="https://user-images.githubusercontent.com/6310197/32832966-3cc0b92c-ca23-11e7-834b-31a711229812.png">

**Steps to replicate**
* On a project with all passing tests run from the VS IDE.
> Observe the output

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-14
Commit Hash: ec3ee1b

Plugins
-------
csharp (0.10.2.nightly-2017-10-26)
```

**Comment by sriv** [comment] 2017-11-15 16:40
possible duplicate of #844

**Closed** 2018-08-16 05:45 UTC
Labels: bug
