### ISSUE TITLE
The reason for current runner not compatible should be given

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1027] opened 2018-05-07 04:06 UTC
**Expected behavior**
This message only says `current runner is not compatible with gauge LSP`.
This can be because 
- runner does not support LSP features yet
- The installed runner version is not compatible with installed gauge

**Actual behavior**
Getting it for a `gauge-js` project with 
```
Gauge version: 0.9.9.nightly-2018-05-04
Commit Hash: 886dc10

Plugins
-------
js (2.2.0)
```
The runner is not compatible because of a version mismatch.
This is not clear with the current message
```
09:28:21.700 notif #0: initialized: current runner is not compatible with gauge LSP
```

**Steps to replicate**
* Open VSCode
* Create a new `gauge-js` project
* Go to definition on a step
> Getting the above error

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-04
Commit Hash: 886dc10

Plugins
-------
js (2.2.0)
```

**Comment by zabil** [comment] 2020-09-02 11:25
Closing as duplicate of https://github.com/getgauge/gauge-vscode/issues/440

**Closed by zabil** 2020-09-02 11:25 UTC
