### ISSUE TITLE
Step parameter converted to number datatype in case the parameter string is all numbers.

### ISSUE THREAD

**Issue by kiranpatil-ic** [getgauge/gauge#2610] opened 2024-09-19 23:32 UTC
**Describe the bug**
E.g `* Set filter to "4578"`

We use the parameter in such a way that you can specify comma separated values & we split them in the step definition. But since updating to the latest gauge/ts, steps where the string parameter is all numeric have started failing.

```
    @Step("Set filter to <commaSeparatedSites>")
    async setFilter(commaSeparatedSites: string) {
        const sitesArray = commaSeparatedSites.split(','); //FAILURE POINT
        //Loop through array & set filter to the specified values
    }
```

**Expected behavior**
The parameter should be parsed as string even though the string is all numeric.

```
Gauge version: 1.6.7
Plugins
-------
html-report (4.3.1)
screenshot (0.3.0)
ts (0.3.4)
xml-report (0.5.1)
```

```
 - Windows 11
 - VSCode Codelens
 - VSCode

**Comment by chadlwilson** [comment] 2024-09-20 00:56
Can you try using an older gauge-ts version to narrow down where the change was introduced? e.g try 0.1.1

**Comment by kiranpatil-ic** [comment] 2024-09-20 01:03
We were using v1.1.0 before we updated to 1.3.4. It was working fine on 1.1. Now I tried downgrading the gauge-ts version but gauge started crashing. So it seems I would also need to downgrade the gauge version from 1.6.7 ?

**Comment by chadlwilson** [comment] 2024-09-20 03:44
Do you mean you were using `0.1.1`? 

Anyway, that's possible that its not compatible - bit hard for me to follow through the other changes. The goal of my question is to figure out if this is a `gauge-ts` problem or a gauge problem, but I think more likely it's there given the way the changes and the way the plugins work, so will move this ticket there for now.

**Comment by chadlwilson** [comment] 2024-09-20 03:46
@zabil actually, I dont have seem to have permissions for gauge-ts. This is probably related to the changes made there I think? Can you give me permissions to that repo, and/or move this ticket there if you agree it's more likely a plugin issue?

**Comment by chadlwilson** [comment] 2024-09-20 03:47
This might be the same issue as https://github.com/getgauge/gauge-ts/issues/187 actually - similar number coercion going on of something expected to bind as a string and then be parsed.

**Comment by chadlwilson** [comment] 2024-09-20 03:49
Will close as a duplicate of https://github.com/getgauge/gauge-ts/issues/187 for now. @kiranpatil-ic if you can supply a simple reproducing case on that issue it may help.

**Closed by chadlwilson** 2024-09-20 03:49 UTC

**Comment by zabil** [comment] 2024-09-20 07:22
> I dont have seem to have permissions for gauge-ts

@chadlwilson for some reason the core team only had read permissions on gauge-ts I've changes that. Please check now.

**Comment by chadlwilson** [comment] 2024-09-20 09:06
> > I dont have seem to have permissions for gauge-ts
> 
> @chadlwilson for some reason the core team only had read permissions on gauge-ts I've changes that. Please check now.

Yeah, this happens when i a repo is transferred. GitHub have added some capability to configure a custom or default "base role" for new/transferred repos recently which applies to all members, but needs to be configured on the org.
