### ISSUE TITLE
AssertionError: expected false to be truthy

### ISSUE THREAD

**Issue by arnaud** [getgauge/gauge#1382] opened 2019-04-05 13:26 UTC
Hi,

First, thank you for this amazing project.
I'm currently relying gauge to work in pair with TestCafé, with an implementation inspired from [this repo](https://github.com/codename-co/test).

It all works good as long as scenarios are passing.
But the issue I'm facing is the following:
As soon as a step is failing, the rest of the scenario fails (which is good, and by design).
But as soon as a step is failing, all next scenarios fail miserably (which is bad and sad, not by design).

### Steps to reproduce

1. Use this gauge+testcafé integration repo @ https://github.com/codename-co/test
2. Use the following dataset:

> specs/healthcheck.spec:
```md
# healthcheck

## scenario 1

* This step should pass
* This step should pass

## scenario 2

* This step should fail

## scenario 1

* This step should pass
```

> in the terminal:
```bash
$ gauge run specs/check
# healthcheck
  ## scenario 1
 Running tests in:
 - HeadlessChrome 75.0.3758 / Mac OS X 10.14.3

 fixture
 ✔ ✔
  ## scenario 2
 ✘
        Failed Step: This step should fail
        Specification: specs/check/healthcheck.spec:10
        Error Message: [object Object]
        Stacktrace:

  ## scenario 3
{"code":"E53","isTestCafeError":true,"callsite":{"filename":"tests/step_implementation.js","lineNum":163,"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"isV8Frames":true},"errMsg":"AssertionError: expected false to be truthy"}
 ✘
        Failed Step: This step should pass
        Specification: specs/check/healthcheck.spec:14
        Error Message: [object Object]
        Stacktrace:

 1 passed (9s)
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	3 executed	1 passed	2 failed	0 skipped

Total time taken: 12.569s
```

> tests/step_implementation.js:
```js
step('This step should pass', async () => {
  await _.expect(true).ok()
})
```

I'm willing to share more if needed, I kindly appreciate any help on this issue that starts making neurons unlink pair by pair,

### Gauge version
```bash
$ testcafe -v
1.1.1

gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
js (2.3.4)
json-report (0.3.0)
screenshot (0.0.1)
```

**Comment by BugDiver** [comment] 2019-04-08 07:14
@arnaud I could replicate the issue. I will try to find out the root cause. I will post my findings here once I have something to share.

**Comment by NivedhaSenthil** [comment] 2019-04-10 04:36
Closing this issue as it is a duplicate of https://github.com/getgauge-examples/gauge-testcafe/issues/2. Refer the testcafe example for fix.

**Closed by NivedhaSenthil** 2019-04-10 04:36 UTC
Labels: in progress
