### ISSUE TITLE
Gauge not installing plugins

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#294] opened 2016-02-08 10:01 UTC
At times, Gauge is not able to install plugins. Do `gauge --install java`, it shows plugin successfully installed. But it doesn't come up on doing `gauge -v`. The respective plugin dir is also not present in `~/.gauge/plugins`.

**OS:** Ubuntu 14.04 64 bit

**Comment by kaustavdm** [comment] 2016-02-12 06:49
Is it downloading and extracting in a wrong location? Or is it not doing anything at all?

**Comment by kaustavdm** [comment] 2016-02-25 12:51
I can only replicate this on `gauge v0.3.2` on a Ubuntu 14.04 64-bit VM running on a Windows box. Upgrading to latest nightly, `v0.3.3.nightly-2016-02-24`, solves it on that machine as well. Downgrading back to `v0.3.2` brings back the issue.

Cannot reproduce this on Ubuntu 14.04 32 bit VM on a OSX box. Cannot reproduce on a Ubuntu 14.04 32 bit desktop.

This may have been a Linux 64-bit package issue on `v0.3.2`, but looks like it has been solved with the latest nightly. Though, I am clueless what fixed it.

I'll close this issue for now, till we can reproduce this it with a newer version of Gauge.

**Closed by kaustavdm** 2016-02-25 12:51 UTC
Labels: bug
