### ISSUE TITLE
Temporary plugin install dir not deleted

### ISSUE THREAD

**Issue by redcue** [getgauge/gauge#281] opened 2016-01-08 15:03 UTC
There is a problem with the plugin installation procedure (at least I guess on \*NIX). During installation a `/tmp/gauge_temp` dir is created **and not deleted afterwards**.

This directory **needs** to be deleted after successful installation of the respective plugin, since it's owned by the user executing `gauge --install`. Another user on this system would not be able to install plugins. 
This is vital for e.g. CI agents running as multiple users.

**Comment by mahendrakariya** [comment] 2016-01-08 15:09
@redcue Could you please let us know which Gauge version you are using?

This seems to be a duplicate of #104, which has been fixed via https://github.com/getgauge/gauge/commit/685a2d489e5c789a1776d94c36a392764d4ec695. This fix has been released in v0.2.1.

**Comment by redcue** [comment] 2016-01-08 15:11
I am indeed using version 0.2.1!

**Comment by redcue** [comment] 2016-01-08 15:14
Are you maybe just **clearing** the /tmp/gauge_temp not **deleting** it?

**Comment by mahendrakariya** [comment] 2016-01-08 15:20
Thanks for confirming the version. We are [deleting the temp dir](https://github.com/getgauge/gauge/blob/master/plugin/install/install.go#L100).

But there are multiple ways to install a Gauge plugin and we may have missed one of the flows. Could you please tell us the command you used to install the plugin?

**Comment by redcue** [comment] 2016-01-08 15:47
`gauge --install java --file PATHTOJAVAPLUGINZIP`

**Comment by mahendrakariya** [comment] 2016-01-08 15:49
Thanks! We will take a look.

**Comment by mahendrakariya** [comment] 2016-01-11 07:29
@redcue Can you install the [latest nightly build](https://bintray.com/gauge/Gauge/Nightly/view) and see if you are still facing this issue?

**Comment by redcue** [comment] 2016-01-11 09:49
Will do! Have to admit though, I'm not quite sure how to exactly reproduce this right now. I've encountered this problem every other day though with 0.2.1... I'll be on the lookout!

**Comment by apoorvam** [comment] 2016-01-14 12:28
@redcue This issue should be fixed now. You can try installing the latest build. 

Closing this for now. Please feel free to re-open issue if you face it again.

**Closed by apoorvam** 2016-01-14 12:28 UTC
