### ISSUE TITLE
Tests in Test Explorer are disappeared during running tests

### ISSUE THREAD

**Issue by ngorska** [getgauge/gauge#1367] opened 2019-03-14 14:26 UTC
### Expected behavior
Tests in text explorer should run correctly and do not disappeared .

### Actual behavior
Tests in Test Explorer are disappeared during running tests. 
I do not know which tests are correct and which are incorrect after running, because the test cases are disappeared.

### Steps to reproduce
1. Run tests in Test Explorer

### Gauge version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
html-report (4.0.2)
screenshot (0.0.1)

I have also nightly (12.03.2019) version of Gauge (0.3.8) extension in Visual Studio - I think the problem can be with this plugin.

**Comment by ngorska** [comment] 2019-03-19 07:57
Could some check this issue?

**Comment by negiDharmendra** [comment] 2019-03-19 09:53
@ngorska I will need some information from you.

- Visual Studio version
- api.log and gauge.log if it is possible for you to share those logs.
- Do you see this problem in newly created project.

My setup is as follows and it works fine for me.
 - Visual Studio Community 2017 (version 15.9.9)
 - Gauge plugin (0.3.7 and also tried with 0.3.8)

**Comment by ngorska** [comment] 2019-03-19 11:29
@negiDharmendra 
Visual studio pro 15.9.8 (my colleague has vs 15.9.9 and has the same problem)
I have the problem in my both projects.
Logs:
[gauge.log](https://github.com/getgauge/gauge/files/2983009/gauge.log)
[api.log](https://github.com/getgauge/gauge/files/2983010/api.log)

**Comment by negiDharmendra** [comment] 2019-03-20 09:21
@ngorska No luck in reproducing this issue. Is it possible for you to provide a sample project where this issue is reproducible?

**Comment by ngorska** [comment] 2019-03-20 09:28
This issue appeared when I upgraded gauge, csharp and gauge extension in vs (versions above).  
Sample proj:
1. I have 4 steps for one test case and when run one of them (RMB->run selected tests), the step disappeared. 
2. When I run next step from this TC, the previous is appeared -> but I do not know if passed or failed.
Sample screen:
![image](https://user-images.githubusercontent.com/16913791/54673606-e2459080-4afa-11e9-9a67-c23f38446efa.png)

**Comment by negiDharmendra** [comment] 2019-03-20 10:37
Hey @ngorska do you see this issue happening in sample project.

Uploading few screen shots here
- before running tests
![before-running-test](https://user-images.githubusercontent.com/15261737/54677519-0e780600-4b29-11e9-9bf9-708f8002018c.PNG)
---
- while running first test.
![while-running-first-test](https://user-images.githubusercontent.com/15261737/54677540-1a63c800-4b29-11e9-9bb3-34653c488be9.PNG)

- after running first test
![after-runing-first-test](https://user-images.githubusercontent.com/15261737/54677560-251e5d00-4b29-11e9-8662-2e7e428169ba.PNG)
---
- while running second test
![while-running-second-test](https://user-images.githubusercontent.com/15261737/54677574-294a7a80-4b29-11e9-8862-1a6096c50b83.PNG)
---
- after running second test
![after-runing-second-test](https://user-images.githubusercontent.com/15261737/54677579-310a1f00-4b29-11e9-9127-e265f33e7478.PNG)

**Comment by ngorska** [comment] 2019-03-20 10:40
Ok I have in sample proj the same situation like You, but in my project the cases are not appeared above all cases :) I do not see which are passed or failed.
My case is disappeared and appeared when run another one.

**Comment by negiDharmendra** [comment] 2019-03-20 12:04
@ngorska How many specs are there in your project. 
Is it possible for you to share your project with us? Or we could get on a call.

**Comment by ngorska** [comment] 2019-03-20 12:32
I can not share my project, sorry. 
I have a lot of specs, but what I said early, this happened when upgraded everything.

**Comment by nehashri** [comment] 2019-03-21 04:52
@ngorska I think what @negiDharmendra would like to know is the number of scenarios/specifications in your project. This will give us a rough idea if the issue is due to a large number of specifications/scenarios. As you see, we don't seem to see this problem in smaller projects.

**Comment by ngorska** [comment] 2019-03-21 06:42
@nehashri 
Hi. ok so I have 20 specifications with 3-5 max scenarios in them, but what I said with previously versions (number of specifications was the same) I did not have this problem.

**Comment by negiDharmendra** [comment] 2019-03-21 09:53
@ngorska Meanwhile we try to replicate it on our end, Is it possible for you to downgrade the Gauge and Gage plugin version and see if it works?

**Comment by ngorska** [comment] 2019-03-21 10:12
@negiDharmendra Ok I downgraded everything, without Gauge plugin version, because available lowest version is 0.3.7.
unfortunately:/ I have the same situation..

**Comment by negiDharmendra** [comment] 2019-03-21 12:46
@ngorska You can download an older version of `Gauge-Visual-Studio` plugin from [here](https://github.com/getgauge/gauge-visualstudio/releases).

**Comment by ngorska** [comment] 2019-03-21 12:56
@negiDharmendra I ran my all spec and it works with gauge plugin 0.3.6.

**Comment by negiDharmendra** [comment] 2019-04-08 07:08
@ngorska We have fixed this issue. Please install the latest nightly from [here](https://bintray.com/gauge/Gauge.VisualStudio/Nightly/latest.nightly-2019-04-08) and let us know if you face the issue again.

**Comment by ngorska** [comment] 2019-04-08 07:12
@negiDharmendra 
Hi 
I installed the newest version and does not work.
I have the same problem.

**Comment by negiDharmendra** [comment] 2019-04-08 07:37
@ngorska Please verify the plugin version it should be 0.3.8.

**Comment by ngorska** [comment] 2019-04-08 07:39
@negiDharmendra yes I have 0.3.8

**Comment by negiDharmendra** [comment] 2019-04-08 08:13
@ngorska Are your tests still disappearing from the test explorer.

**Comment by ngorska** [comment] 2019-04-08 08:24
@negiDharmendra
I ran my tests and still disappearing:(

**Comment by negiDharmendra** [comment] 2019-04-08 09:41
@ngorska Please see the attached recording.
[latest plugin demo.zip](https://github.com/getgauge/gauge/files/3053680/latest.plugin.demo.zip)

**Comment by ngorska** [comment] 2019-04-08 09:50
@negiDharmendra I did the same steps as you and is not working.

**Comment by negiDharmendra** [comment] 2019-04-08 10:20
@ngorska Does it work after building the solution.

**Comment by ngorska** [comment] 2019-04-08 10:20
@negiDharmendra yes :(

**Comment by negiDharmendra** [comment] 2019-04-08 10:26
@ngorska Please share a recording with a sample`gauge-csharp` project.

run `gauge init csharp` command to create a sample project.

**Comment by negiDharmendra** [comment] 2019-04-08 10:30
@ngorska You can also reach out to us through [this gitter  community](https://gitter.im/getgauge)

**Comment by ngorska** [comment] 2019-04-08 12:35
@negiDharmendra I ran the sample proj and it works, but my tests not :(

**Comment by negiDharmendra** [comment] 2019-04-09 05:57
@ngorska Please run your `gauge specs` from the command line with `--machine-readable` flag and share the output( including gauge.log file) with us. Please remove any sensitive information you don't want to share.

I would recommend you to join our [community](https://gitter.im/getgauge) on Gitter.

**Example:**
`gauge run --machine-readable`

**Comment by ngorska** [comment] 2019-04-10 07:39
@negiDharmendra 
Hi this is gauge.log
[gauge.log](https://github.com/getgauge/gauge/files/3062525/gauge.log)
and this is output from console ( I want to mention that the tests run correctly from console.)
[outputconsole.txt](https://github.com/getgauge/gauge/files/3062544/outputconsole.txt)

**Comment by Debashis9012** [comment] 2019-04-12 15:43
This issue has been verified and found fixed with the below version
``` gauge.visualstudio-latest.nightly-2019-04-08 ```

**Comment by ngorska** [comment] 2019-04-15 05:41
@Debashis9012 Hi I wrote a few days ago that this version did not help.

**Comment by Debashis9012** [comment] 2019-04-16 05:47
Reopening this issue as @ngorska faces the same problem in her project with the fix version.

**Comment by Debashis9012** [comment] 2019-06-28 06:45
@ngorska  could you please try with the release version of visual studio plugin:
https://github.com/getgauge/gauge-visualstudio/releases/tag/v0.3.8 and let us know if you are still facing the same issue.

**Comment by ngorska** [comment] 2019-06-28 07:14
@Debashis9012 hi I have it and it does not work.

**Comment by Debashis9012** [comment] 2019-06-28 08:29
@ngorska may i know which version of gauge you are using ?
If you are using older version of gauge we would suggest you to try with the latest nightly gauge version: https://bintray.com/gauge/Gauge

**Comment by ngorska** [comment] 2019-06-28 08:49
@Debashis9012 I have 1.0.5.
I can not install 1.0.6
I did the same things as always to install gauge but now I can not.
![image](https://user-images.githubusercontent.com/16913791/60330280-65943f00-9992-11e9-83c7-296daf122142.png)

**Comment by shubhamsc** [comment] 2019-07-08 12:15
@ngorska You can install only the released version of Gauge with Chocolatey. Gauge v1.0.6 isn't released yet.
For installing the nightly version of Gauge please look the [docs](https://docs.gauge.org/latest/installation.html).

**Comment by Apoorva-GA** [comment] 2019-07-26 08:58
@ngorska Did you get a chance to try this out with the latest nightly version?

**Comment by ngorska** [comment] 2019-07-31 06:19
@Apoorva-GA hi yes I have it installed but not working.
The tests are still disappearing during running tests

**Comment by shubhamsc** [comment] 2019-08-07 06:41
@ngorska Please make sure you are using the latest nightly version of gauge, gauge-csharp and gauge visual-studio plugin. If you are still seeing the same issue please share the log files.
Sharing a sample project really help us to replicate the issue.

**Comment by ngorska** [comment] 2019-08-08 12:17
@shubhamsc  
Hi I have installed all latest nightly version of gauge 
![image](https://user-images.githubusercontent.com/16913791/62702497-2de3d280-b9e7-11e9-9305-4ba25a1e25f1.png)

but still not working, sorry :( 
log 
[gauge.log](https://github.com/getgauge/gauge/files/3481634/gauge.log)

**Comment by ngorska** [comment] 2019-08-08 12:18
I do not know what happened but I did not close the ticket :/

**Comment by MZar2019** [comment] 2019-09-11 13:38
Visual Studio Test Explorer has icons that control what tests are shown, make sure what you want to see is selected. For example, if you unselect the green checkbox, tests will disappear as they pass.

![te](https://user-images.githubusercontent.com/52498077/64702086-c1814680-d45e-11e9-8f34-f7b9023d4254.png)

**Comment by sriv** [comment] 2020-03-16 04:31
Some updates:

Both  gauge-csharp and gauge-dotnet plugins have been deprecated in favour of gauge-dotnet and gauge-vscode respectively.

Closing this issue, as Gauge team will not be maintaining the gauge-visualstudio plugin.

**Closed by sriv** 2020-03-16 04:31 UTC
Labels: bug

**Comment by shirishnagarnz** [comment] 2020-05-17 19:49
Hi,

I came across this issue 2 days back when upgraded VS 2019 version from 16.5.4 to 16.5.5.

Any solution? Below is the copied info,

Microsoft Visual Studio Enterprise 2019
Version 16.5.5
VisualStudio.16.Release/16.5.5+30104.148
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
