### ISSUE TITLE
Add support for defining test data

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#94] opened 2015-02-20 15:28 UTC
Have a way to define complex test data that can be used as a reference in specs. Table based data works for flat, repeated data.

Consider having a YAML/JSON file, that Gauge would parse and would either pass to the runner as a test data object or have an api to look up against.

The YAML/JSON definition should contain a key, and Gauge should be able to de-serialize this data.

Helps writing succinct Steps, without writing verbose setup steps/code.

**Comment by teknologika** [comment] 2015-07-23 05:51
This is really important for a couple of reasons.

1. Separation of concerns .. test data should not be mixed in with the test case itself.
2. Allowing tests to be "data driven" with large, datasets.

I think that a good implementation would be to allow an abstracted "data source" to be utilised. What I am thinking from a practical point of view is how can I use a parwise or random generator to generate the test data, as well as a set of "known good" test data.

Data sources I am thinking of are: CSV, JSON, YML and a SQLite database.

**Comment by ColOfTheDead** [comment] 2016-11-22 23:47
Support for JSON files at a minimum would be a huge step forward.

**Comment by jackperalta** [comment] 2018-04-10 10:45
I'm wondering whether this is now doable with https://github.com/getgauge/gauge-java/issues/140

given the following json file (or any other format you like)

```
{
    "userName" : "John Doe"
}
```
and a custom parser like
```
public class PersonGaugeParser extends CustomParameterParser<Person> {
    @Override
    public boolean canParse(Class<?> aClass, Spec.Parameter parameter) {
        return aClass.equals(Person.class);
    }


    @Override
    protected Person customParse(Class<?> aClass, Spec.Parameter parameter) {
        return new Gson().fromJson(parameter.getValue(), (Class<? extends  Person>) aClass);
    }
}
```
one can now use as step implementation
``` 
@Step("Create from file <file:person.json>")
public void fromFile(Person person) {
      Assert.assertEquals(person.getUserName(), "John Doe");
}
```
is this what the issue is about ?

**Comment by nehashri** [comment] 2018-04-11 08:28
@jackperalta It does address the issue partially. It is still upto the user to define these parsers. It would be helpful to have a few of these parsers bundled with Gauge.

**Comment by sguptatw** [comment] 2018-04-13 03:57
**Observation**
Gauge tests can be written and run in multiple languages. Java, C#, Ruby, Javascript and Python are the officially supported language runners.

@jackperalta - The issue getgauge/gauge-java#140 deals with parsing Custom types for Java.

**Suggestion**
The following suggests one approach for this. This implementation will have 2 steps
In Gauge-core
- Have a JSONObject in Gauge. JSON parameters are converted to set of map values here.
The language runners
- Handling this format in languages Javascript, Ruby, Python is straightforward. Java & C# language runners will have to handle converting it to the corresponding Custom type.

**Comment by sguptatw** [comment] 2018-04-13 05:51
In the approach mentioned above, Gauge is responsible for recognizing `convert from` format i.e String or JSON. The parsers in the language runners will find the `convert to` format and perform the parsing.

In the approach given below, the individual language runners will be responsible for recognizing `convert from and to` formats and the parse it.

**Another approach**
Today when <file:user.json> parameter is used, Gauge passes the contents of the file as the parameter value. The language runners parse the parameter and do the required conversion.

> Currently Javascript, Python and Ruby language runners do not have custom parsing parameters.

> Custom Parameter parsing is available in Java  - getgauge/gauge-java
> Today, the c# runner attempts to convert the parameter to any type that is IConvertible

**Comment by ajoecker** [comment] 2019-01-15 05:45
my comment at #1242 is not helping you (directly) in your case. You are able to load any data format currently in gauge and then access the data in your step. But a way of defining the access of the data inside the spec (`fixtures[admin_email`) is not possible.

Bear in mind that I do not know how this can be done/should be done in JavaScript, but like in Java you can read in your source - automatically inside a @BeforeSpec/BeforeSuite annotated method - or in a seperate step and hold this data in your application (for example with datastores).

Let's try an example:

```
# This is a spec
* Load data from "config.yaml"
##
* Login as admin
```

```
public class GaugeImplementation {
 private Map<String, Object> dataHolder = new HashMap<>();

@Step("Load data from <inputFile>") {
 public void loadData(String inputFile) {
   dataHolder = loadDataHowSoEver(inputFile); // how every you read the yaml file or any other source
}
 
@Step("Login as admin") 
public void loginAdmin() {
   dataHolder.get("admin_email"); // get data and proceed with the configured values
}
}
```

Datastores allow, as the name implies, to store date between steps or even specs - you can see them as global storage units - one step is putting data in, another is accessing it.

Languages like java support this already out of the box as shown above

**Comment by NicholasEF** [comment] 2019-01-16 22:38
Hm OK, thanks. I think I am doing essentially the same thing, setting my data to a variable or hash at the top of the JS step implementation code, but skipping the need for a "load data" step, and just accessing it directly in the login step and others.

**Comment by zabil** [comment] 2020-03-04 10:23
This will be partially solved when implemented using code blocks https://github.com/getgauge/gauge/issues/1240

**Closed by zabil** 2020-03-04 10:23 UTC
Labels: feature

**Comment by h3tz** [comment] 2021-05-11 11:23
Why this is closed when only partly a solution is available?
