### ISSUE TITLE
Unable to install JS Plugin

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/gauge#1296] opened 2019-01-08 18:35 UTC
**Objective**
Install Gauge JS plugin offline

**Expected behavior**

Plugin should install successfully

**Actual behavior**
Installation is throwing error message and exits without installing
Steps to reproduce
1.	Open command command and navigate to the folder where JS plugin's zip file is saved
2.	Run command gauge install js --file gauge-js-2.3.3.zip and hit enter
3.	It starts installation but then exits with below error message

Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\mghai\AppData\Lo
cal\Temp\1\gauge_temp1546960633750306200\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\mghai\AppData\Local\Temp\1\gauge_temp154696063
3750306200\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)

Failed to install plugin 'js'
Reason: exit status 1
Gauge version
Gauge version: 1.0.2
Commit Hash: b4288bb

**Plugins**
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)

**Comment by sriv** [comment] 2019-01-09 06:59
duplicate of https://github.com/getgauge/gauge-js/issues/182

**Closed by sriv** 2019-01-09 06:59 UTC
Labels: community
