### ISSUE TITLE
Feature Request: Fetch CSV file from specific file path BeforeSuite.

### ISSUE THREAD

**Issue by Vishnu1067** [getgauge/gauge#987] opened 2018-03-26 02:51 UTC
### Expected behavior
CSV file will generate outside work repo and want to fetch the file before executing the test.

### My Scenario:
1. Developer will generate the json file and mention the CSV file path in it
2. Then I will get the file path using jSON object and set to `<file:file_path>`
3. If we implement this feature in step implementation, i can write custom function to get the file path then start executing test cases.

### Specs

```* Given I will get the csv file path```

### Step

```
@Step("Given` I will get the csv file path")
public void getCSV() {

JSONObject jsonObj = new JSONObject();
String file = jsonObj.getJSONObject(filepath).tostring();

Table csv = new Table(file) -- required new feature to specify the file path and create Table obj.
csv.getRows(); -- existing feature in gauge
csv.getColname();

```

**Comment by sriv** [comment] 2019-01-14 06:35
I read the original description to have a feature by which the `table` csv file can be generated/fetched as part of `gauge run` or `gauge validate` commands. This gives the user the ability to get data that is probably more recent and contextual. @Vishnu1067 - is my understanding correct?

However, from what you describe @osandadeshan, I believe that the `csv` files should be allowed to be mutated by a scenario, and gauge should include the changes for subsequent scenarios? If my understanding is correct, then I think this might yield some problems:

- introduce dependdency between scenarios (gauge recommends that scenarios should be independent)
- introduce cyclic dependencies. tables are use for data driven execution as well (although you may be referring to just the usage of table as parameters, but there is an overlap between the two in how gauge uses these). manipulating the source of table driven execution in a scenario can lead to infinite recursion.
- `rerun` and `failed` flags will be broken. and these are semantic regression, i.e. the underlying concept will be different. 
- a single scenario cannot be run if it consumes output of another scenario

I believe it is probably better to use a separate mechanism, and not overload gauge's mechanism to address this.

Does this make sense? please correct if I'm mistaken. thanks.

**Comment by delmaamoun** [comment] 2020-01-17 16:02
@sriv I'm having a similar problem. I need to get the most recent data and use that for data driving. For example, I need to connect to the database and get available shop items and then run a scenario/spec against those.
The only way I can imagine doing that would be to run the DB fetch in a @beforesuite step and write that in a csv file that is passed to the scenario/spec, this doesn't work because only the snapshot of the file before it's rewritten is used.
My (bigger) problem is that I also need a concept to run in @beforesuite.
I see your points, but what would be the ideal way to get live data to use for the tests then?

**Comment by zabil** [comment] 2020-01-17 17:32
@delmaamoun It's best done outside Gauge. Write a program that will generate the csv files and then run Gauge. Things can go wrong while fetching data in between tests. It will be much easier and deterministic to debug and rerun tests with fixed data.

**Comment by zabil** [comment] 2020-07-17 13:59
Closing this issue and Gauge will not be able to implement this as csv files are required while parsing the specs. As Gauge does not checks spec validity at run time it won't be able to allow a feature that supports modifying csv inputs or paths.

**Closed by zabil** 2020-07-17 13:59 UTC
Labels: feature
