### ISSUE TITLE
Cant start tests

### ISSUE THREAD

**Issue by marek2209** [getgauge/gauge#299] opened 2016-02-19 10:37 UTC
I cant debug and start tests
![image](https://cloud.githubusercontent.com/assets/9087374/13173292/0df45f6a-d6fd-11e5-8bec-4c3bb7272b16.png)

**Comment by sriv** [comment] 2016-02-19 13:32
Is the project built before running the tests? This error indicates that Gauge VS is unable to locate the project's output path

**Comment by marek2209** [comment] 2016-02-19 13:32
Yes i do rebuild also

**Comment by marek2209** [comment] 2016-02-19 13:33
1>  gaugePreview -> C:\Users\\Documents\Visual Studio 2015\Projects\gauge-preview\bin\Debug\gauge-preview.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by kaustavdm** [comment] 2016-02-19 18:46
Closing as a possible duplicate of getgauge/gauge-csharp#49. Please reopen if this needs to be tracked in gauge than the issue reported in the gauge-csharp issue tracker.

**Closed by kaustavdm** 2016-02-19 18:46 UTC

**Comment by marek2209** [comment] 2016-02-19 18:48
This is not a duplicate... I see tests but i cant start it look at the picture
