### ISSUE TITLE
Show Diagnostics LSP

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#823] opened 2017-09-27 10:51 UTC
Gauge LSP server should support publish diagnostics for spec and concept files.
The server should publish diagnostics when the document changes.
This story is part of [LSP support](https://github.com/getgauge/gauge/issues/717) for gauge.

## Test cases

- [x] Should show critical errors
- [x] Should show spec parse errors
- [x] Should show concept parse errors
- [ ] Should show unimplemented steps
- [ ] duplicate step definition

**Comment by BugDiver** [comment] 2017-11-09 09:42
Currently diagnostics for error `Should show unimplemented steps`  and ` duplicate step definition` is shown only for Javascript.

Fix should be available with following nightlies =>
 gauge      => 09-1-2017
 gauge-js => 09-1-2017

**Comment by sguptatw** [comment] 2017-11-14 06:06
Issues
- [ ] Unimplemented step is not getting highlighted
- [ ] Duplicate step implementation is not being shown
- [ ] Number of usages are also not displayed

[test1.zip](https://github.com/getgauge/gauge/files/1469724/test1.zip)

**Comment by Apoorva-GA** [comment] 2017-11-15 06:14
Please reopen the spec file or edit the spec file for the errors to get highlighted, because diagnostics load when there a file change or when you open the file.

**Comment by sguptatw** [comment] 2017-11-15 09:33
Closing this issue as the unimplemented step is working as designed.
Unable to replicate the duplicate step issue consistently.

**Comment by sguptatw** [comment] 2017-11-15 14:41
Getting diagnostics on wrong lines
Getting step implementation not found on the wrong line

<img width="421" alt="parseerrorwrongline" src="https://user-images.githubusercontent.com/6310197/32841709-114d0e1c-ca41-11e7-888c-658a5dc72358.png">

[test1.zip](https://github.com/getgauge/gauge/files/1475077/test1.zip)

**Comment by sguptatw** [comment] 2017-11-15 14:55
Getting step implementation not found on existing valid steps.
![StepImplementationNotFound.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db809f33ab8eb983ecb246aa49f1802049295d26108524658be76af3006b1300051bff054a5556f9ff8c7faeb76a25dc5f58b8856d5b72c63d15fdbbd11abd13a632c91edbe2e3d7158abd7f37ed998d4d341f001989f85832a6904aca5cfe59ac.png)

**Comment by sguptatw** [comment] 2017-11-16 03:23
Getting a duplicate step implementation on a step that is not implemented
<img width="292" alt="wrongduplicatestepimpl" src="https://user-images.githubusercontent.com/6310197/32872207-7cd15a20-caab-11e7-893b-85d53002911a.png">
[test1 (2).zip](https://github.com/getgauge/gauge/files/1477203/test1.2.zip)

**Comment by sguptatw** [comment] 2017-11-16 03:38
Getting a duplicate concept defined even if one of the folders is configured in gauge_exclude_dirs

**Comment by nehashri** [comment] 2017-11-20 11:26
## Change in way diagnostics are published 
All files are validated and diagnostics are published for all files.

Diagnostics are published when
- when gauge lsp server is initialized
- a gauge file(.spec and .cpt) is opened
- any file is changed (gauge or implementation files)

**Comment by Apoorva-GA** [comment] 2017-11-21 08:11
Available in gauge nightly >= 20/11/17.
please check if commit hash `b306205`

**Comment by sguptatw** [comment] 2017-11-21 14:57
Switching between a js file and spec file gives step not implemented error.

**Steps to replicate**
* Checkout project [LSP tests](https://github.com/getgauge/gauge-lsp-tests.git)
* Open diagnostics.js
* Open autocomplete.spec
> Observe the errors on all steps

**Comment by sguptatw** [comment] 2017-11-21 15:28
Steps with duplicate step implementation does not show the error

**Steps to replicate**
* Project - [test1 (2).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46fc918937d3c3e1dda0fd0fe64de29b234324676b5ee17e26d0e770ee447e075c0c1bf8415c5944fcfdd828f5b33e62964e49bc8f3900299f7744eeaa880dbe06b0218e4e84b4bb824cc0ea3f23e099c2.zip)
* Open in VSCode
> Observe there are duplicate step implementations for all steps.
However no error is displayed on the spec files

**Comment by sguptatw** [comment] 2017-11-21 23:41
The duplicate step implementations do not go away when a file with the duplicate steps are deleted.
**Steps to replicate**
* Project - [test1 (2).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46fc918937d3c3e1dda0fd0fe64de29b234324676b5ee17e26d0e770ee447e075c0c1bf8415c5944fcfdd828f5b33e62964e49bc8f3900299f7744eeaa880dbe06b0218e4e84b4bb824cc0ea3f23e099c2.zip)
* Open in VSCode
* Delete the new_test.js
* Close all files
* Open the spec file
> Observe there are duplicate step implementations are still there.

**Comment by sguptatw** [comment] 2017-11-21 23:51
Duplicate concept definitions are not indicated

**Steps to replicate**
* Project - [test1 (2).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46fc918937d3c3e1dda0fd0fe64de29b234324676b5ee17e26d0e770ee447e075c0c1bf8415c5944fcfdd828f5b33e62964e49bc8f3900299f7744eeaa880dbe06b0218e4e84b4bb824cc0ea3f23e099c2.zip)
* Open in VSCode
The concept named `Concept` has duplicate definitions.
* Open the concept files `one.cpt` and `newConcept.cpt`. 
> Observe they do not indicate the duplicate `Concept` definitions.

**Comment by sguptatw** [comment] 2017-11-22 04:36
**Expected behavior**
Concept Circular reference should be shown in a both usages.

**Actual behavior**
Circular reference is shown only on one usage

**Steps to replicate**
* Create concepts with circular reference
```
# Concept1
* Concept2

# Concept2
* Concept1
```

**Comment by sguptatw** [comment] 2017-11-22 05:20
**Expected behavior**
Deletion of a code file should update the step definitions accordingly

**Actual behavior**
Getting an existing connection forcibly closed
![ExistingConnectionClosed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46cd8c9330968aa788cab04daa58f38020492950250bb02e74c7af6aaf50740b0a0c0abe4b4a5a42f9ad812af0e36a73d9095fedd56b5f74c26c12ffbd800da313f871d51bdaebe5c01982fa3737e68c854e3b1f041b8bf85a33a19148cd4abb.png)

**Steps to replicate**
* On a new project
* Copy paste step_implementation.js into the same project
* Close all files
* Select step_implementation.js file. Delete it permanently
* Open example.spec file
> Observe red lines indicating that existing connection was forcibly closed

**Comment by Apoorva-GA** [comment] 2017-11-22 11:16
Fix should be available in gauge and gauge-js nightly >= 22/11/17

**Closed** 2017-11-24 06:12 UTC
Labels: lsp
