### ISSUE TITLE
VS code 

### ISSUE THREAD

**Issue by marek2209** [getgauge/gauge#344] opened 2016-04-19 10:37 UTC
Hi if is it any possibility to create plugin for Visual Studio Code for gauge ? (syntax highlighting etc.)

**Comment by mahendrakariya** [comment] 2016-04-19 10:44
We already have an open issue (#264) for VSCode. It'd be great if someone from the community could contribute to this.

I am also closing this issue because it is a duplicate of #264.

**Closed by mahendrakariya** 2016-04-19 10:44 UTC
Labels: duplicate
