### ISSUE TITLE
Multiple spec files in the command line executes only one

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#69] opened 2015-01-21 09:48 UTC
```
gauge specs/first.spec specs/second.spec
```

In this case, only `second.spec` gets executed

**Comment by prateekbaheti** [comment] 2015-01-23 09:28
This has been resolved in the latest gauge. Could you build from source and try. Cannot reproduce it.

**Comment by prateekbaheti** [comment] 2015-02-04 12:26
Closing this issue. Has been resolved.

**Closed by prateekbaheti** 2015-02-04 12:26 UTC
Labels: bug
