### ISSUE TITLE
Not able to run java project from both VSCode and Command Line

### ISSUE THREAD

**Issue by manavghaigit** [getgauge/gauge#1774] opened 2020-10-15 21:42 UTC
I am doing Gauge/Java for the first time. Installed Gauge, Installed VSCode, Installed VSCode Plugin. I installed JDK as well version (jdk-11.0.7).

I tried to run from both VSCode and command line but Gauge is not doing anything at all. Below is the log from gauge's log file. It starts the execution but does not do anything.

***********************************************************************************************************************************
15-10-2020 17:52:56.403 [Gauge] [DEBUG] Created gauge_screenshots_dir at C:\Users\ghaima2\Desktop\Automation\Gauge\Java\New folder\.gauge\screenshots
15-10-2020 17:52:56.405 [Gauge] [DEBUG] Plugin java is already installed.
15-10-2020 17:52:56.406 [Gauge] [DEBUG] Plugin html-report is already installed.
15-10-2020 17:52:56.406 [Gauge] [DEBUG] Parsing started.
15-10-2020 17:52:56.406 [Gauge] [DEBUG] Started concepts parsing.
15-10-2020 17:52:56.408 [Gauge] [DEBUG] 0 concepts parsing completed.
15-10-2020 17:52:56.410 [Gauge] [DEBUG] Started specifications parsing.
15-10-2020 17:52:56.411 [Gauge] [DEBUG] 1 specifications parsing completed.
15-10-2020 17:52:56.411 [Gauge] [DEBUG] Parsing completed.
15-10-2020 17:52:56.693 [java] [DEBUG] ***** Printing Properties/Env Values *****
15-10-2020 17:52:56.694 [java] [DEBUG] PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\app\oracle\product\11.2.0\client_1\bin;C:\Informatica\10.4.0\clients\tools\datadirect;C:\Informatica\10.4.0\clients\tools\odbcdrv;C:\Informatica\10.4.0\clients\tools\jdbcdrv;C:\Informatica\10.4.0\clients\tools\sharedlibs;C:\Program Files\Microsoft MPI\Bin\;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\PuTTY\;C:\Program Files\Collaborator Client;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Common Files\ThinPrint\;C:\Program Files\ibm\gsk8\lib64;C:\Program Files (x86)\ibm\gsk8\lib;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION;C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Gauge\bin;C:\Users\ghaima2\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk-11.0.7\bin;;C:\Users\ghaima2\AppData\Roaming\gauge\plugins\screenshot\0.0.1
15-10-2020 17:52:56.694 [java] [DEBUG] JAVA_HOME: 
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_project_root: C:\Users\ghaima2\Desktop\Automation\Gauge\Java\New folder
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_parallel_streams_count: 2
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_reports_dir: reports
15-10-2020 17:52:56.694 [java] [DEBUG] overwrite_reports: true
15-10-2020 17:52:56.694 [java] [DEBUG] logs_directory: logs
15-10-2020 17:52:56.694 [java] [DEBUG] enable_multithreading: false
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_specs_dir: specs
15-10-2020 17:52:56.694 [java] [DEBUG] csv_delimiter: ,
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_java_home: 
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_custom_build_path: 
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_additional_libs: libs/*
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_jvm_args: 
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_custom_compile_dir: 
15-10-2020 17:52:56.694 [java] [DEBUG] gauge_clear_state_level: scenario
15-10-2020 17:52:56.694 [java] [DEBUG] ***** END *****
15-10-2020 17:52:56.724 [java] [DEBUG] running - javac.exe [-encoding UTF-8 -d gauge_bin @C:\Users\ghaima2\AppData\Local\Temp\gauge_temp023471027\52fdfc072182654f163f5f0f9a621d72]
15-10-2020 17:52:56.724 [java] [DEBUG] stdout/stderr is logged to logs\1920-javac.exe.out
15-10-2020 17:52:56.803 [Gauge] [DEBUG] Checking updates...
15-10-2020 17:52:56.805 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=amd64
15-10-2020 17:52:56.904 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=amd64
15-10-2020 17:52:56.926 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/json-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=amd64
15-10-2020 17:52:56.963 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=amd64
15-10-2020 17:52:57.026 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/xml-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=amd64
15-10-2020 17:52:58.915 [java] [DEBUG] classpath set to C:\Users\ghaima2\AppData\Roaming\gauge\plugins\java\0.7.12\*;C:\Users\ghaima2\AppData\Roaming\gauge\plugins\java\0.7.12\libs\*;C:\Users\ghaima2\Desktop\Automation\Gauge\Java\New folder\libs\*;gauge_bin
15-10-2020 17:52:58.915 [java] [DEBUG] found java executable in java.exe
15-10-2020 17:52:58.915 [java] [DEBUG] running - java.exe [-Dfile.encoding=UTF-8 com.thoughtworks.gauge.GaugeRuntime --start]
15-10-2020 17:52:58.915 [java] [DEBUG] stdout/stderr is logged to logs\1920-java.exe.out
15-10-2020 17:52:59.568 [java] [DEBUG] multithreading is set to false
15-10-2020 17:53:00.040 [java] [DEBUG] Using reflection to scan dependencies for gauge implementations...
15-10-2020 17:53:01.116 [java] [DEBUG] gauge-java took 1433milliseconds to load and scan. This should be less than 'runner_connection_timeout' config value.
15-10-2020 17:53:01.116 [java] [DEBUG] run 'gauge config runner_connection_timeout' and verify that it is < 1433
15-10-2020 17:53:01.156 [java] [DEBUG] starting gRPC server...
15-10-2020 17:53:01.689 [java] [DEBUG] started gRPC server on port 57715
15-10-2020 17:53:01.689 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 57715
15-10-2020 17:53:01.864 [Gauge] [DEBUG] Successfully made the connection with runner with port: 57715
15-10-2020 17:53:01.864 [Gauge] [DEBUG] Validation started.
15-10-2020 17:53:02.165 [java] [DEBUG] Scanning packages for steps
***********************************************************************************************************************************

Attached is the screenshot from command line and vscode showing it does not do anything.

Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
html-report (4.0.12)
java (0.7.12)
json-report (0.3.5)
screenshot (0.0.1)
xml-report (0.2.3)
[Gauge Java.docx](https://github.com/getgauge/gauge/files/5388045/Gauge.Java.docx)

**Comment by BugDiver** [comment] 2020-10-19 05:11
@manavghaigit Looking at the logs and the screenshot it seems like the scanning is taking too much time (or may be not finishing at all) for some reasons. Could you please give us a sample project to replicate it? I'm not able to replicate it on my machine with a sample project.

**Comment by manavghaigit** [comment] 2020-10-19 10:57
@BugDiver  It’s a default project created using “gauge init java”

**Comment by manavghaigit** [comment] 2020-10-20 14:23
@BugDiver Request to please advise on what else could be the problem? This is a base project created using "gauge init java"

**Comment by zabil** [comment] 2020-10-20 15:14
From the screenshots it looks like the gauge plugin is initialised as the IDE is working. 

It could be the JDK that was installed or the way Java is launched. Can you try installing a higher version of the JAVA JDK and make sure the right JDK path is set on the PATH environment variable?

**Comment by manavghaigit** [comment] 2020-10-20 17:08
@zabil I currently have "jdk-11.0.7" installed on my machines. Is there any specific version you would like to recommend?

**Comment by zabil** [comment] 2020-10-21 14:21
> I ran it on a new machine today and only through CMD but still got the same issue. I currently have "jdk-11.0.7" installed on my machines. Is there any specific version you would like to recommend?

Are you running this inside a virtual machine? I did come across this when I tried to replicate the issue on virtualbox. This happened because the windows firewall was blocking access to the java process and the runner was timing out. I was able to get over this by increasing the timeout with the following command. And giving access to the firewall to accept connections(it pops up a box).

```
gauge config runner_connection_timeout 300000000
```

> One thing i would like to mention, after installing JDK it did not automatically add JDK bin folder path to PATH variable in System Variables so i had to add it manually. Not sure if it matters.

This shouldn't matter. I tested this by installing JDK 14 using the following command, this uses [chocolatey](https://chocolatey.org). Chocolatey was installed by default on the Official Microsoft VM images.

```
choco install openjdk14
```

Please try these options.

**Comment by manavghaigit** [comment] 2020-10-21 16:44
@zabil Yes i am running it on VDI. I tried your recommendation of increasing timeout but its stopping at the same stage. You mentioned about opening access to java process in firewall. Can you please shed some light on how to do it?

21-10-2020 12:33:47.773 [java] [DEBUG] starting gRPC server...
21-10-2020 12:33:48.090 [java] [DEBUG] started gRPC server on port 60382
21-10-2020 12:33:48.090 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 60382
21-10-2020 12:33:48.550 [Gauge] [DEBUG] Successfully made the connection with runner with port: 60382
21-10-2020 12:33:48.550 [Gauge] [DEBUG] Validation started.
21-10-2020 12:33:49.194 [java] [DEBUG] Scanning packages for steps

**Comment by zabil** [comment] 2020-10-22 09:02
> I tried your recommendation of increasing timeout but its stopping at the same stage. You mentioned about opening access to java process in firewall. Can you please shed some light on how to do it?

I don't have access to VDI. You might have to google that.
My guess is the are a few issues here with the Java set up 

* The java version mismatches
* Firewall access settings.

These are tricky especially in virtual machine environments where the environment settings are secure by default. Gauge uses grpc to communicate and this will require tweaking the firewall settings for it to work correctly. Unfortunately this is beyond the scope of fixing it in Gauge. I am closing this issue and this has to do with configuration. But please feel free to discuss it further.

**Closed by zabil** 2020-10-22 09:02 UTC

**Comment by manavghaigit** [comment] 2020-10-22 19:00
@zabil _Firewall access settings.
These are tricky especially in virtual machine environments where the environment settings are secure by default. Gauge uses grpc to communicate and this will require tweaking the firewall settings for it to work correctly._

I can work with my network team to look at firewall settings. But they will need to know what is needed here. Can you please through more light on whats needs to be looked into firewall settings so they can proceed accordingly?

**Comment by sriv** [comment] 2020-10-23 01:33
Can you try setting JAVA_HOME env variable in User Environment Variables to JDK 11? Your debug logs seem to indicate that java home is not set?  But the `java.exe` is getting picked up because PATH contains `C:\Program Files\Java\jdk-11.0.7\bin`

**Comment by manavghaigit** [comment] 2020-10-23 16:04
@zabil So JAVA_HOME was a problem and it started working the moment i created this in environment variable. I suggest to mention it as part of the documentation. It took me three days to solve a simple problem. 

Everything seems to be working fine but i am getting this below message in VSCode. can you please advise? This is the project i created using "Gauge init java"
----------------------------------------------------------------------------------------------------
Gauge could not initialize. Install 'vscjava.vscode-java-pack' extension for code insights. For more information see[Problems](command:workbench.actions.view.problems), check logs.[Troubleshooting](https://docs.gauge.org/troubleshooting.html?language=javascript&ide=vscode#gauge-could-not-initialize-for-more-information-see-problems)

**Comment by sriv** [comment] 2020-10-23 16:20
`vscjava.vscode-java-pack` is the ID of vscode's Java language support extension. You should.install it so that you get Java's intellisense on vscode.

See: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

Gauge extension prompts you to do this.

**Comment by manavghaigit** [comment] 2020-10-23 17:37
@sriv @zabil I have already installed vscjava.vscode-java-pack from Extensions in VSCode but i still keep getting this message. I tried uninstalling/reinstalling it but the problem persists. Also i am not getting debug scenaio/spec option in spec file.

**Comment by sriv** [comment] 2020-10-23 17:39
What do the logs say now?

**Comment by manavghaigit** [comment] 2020-10-23 18:35
@sriv I uninstalled/reinstalled again and restarted VSCode and the error has stopped coming up. However i am getting another issue.

I have all my selenium jar files in Gauge's libs folder and i have define reference to all the jar in .classpath file and properly saved the file. 
1. Is this the right way of storing and defining external jars in Gauge? 

2. The problem is every time i reopen folder or vscode, all the selenium jars references gets removed automatically from .classpath file and i am not able to figure out what is causing it. Below is the structure of the .classpath file which it reverts  back to.
-------------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="src" path="src/test/java"/>
	<classpathentry kind="lib" path="C:/Users/ghaima2/AppData/Roaming/gauge/plugins/java/0.7.12/libs/assertj-core-3.17.2.jar"/>
	<classpathentry kind="lib" path="C:/Users/ghaima2/AppData/Roaming/gauge/plugins/java/0.7.12/libs/gauge-java-0.7.12.jar"/>
	<classpathentry kind="output" path="gauge_bin"/>
</classpath>
-------------------------------------------------------------------------------------------------------------------------------

**Comment by zabil** [comment] 2020-10-24 06:24
> So JAVA_HOME was a problem and it started working the moment i created this in environment variable. I suggest to mention it as part of the documentation. It took me three days to solve a simple problem.

It's already documented here https://docs.gauge.org/troubleshooting.html?os=linux&language=javascript&ide=vscode#gauge-could-not-initialize-for-more-information-see-problems


> Is this the right way of storing and defining external jars in Gauge?

Yes, but rarely used. Most users use Gauge and Selenium with a build tool like maven which manages the dependencies. You can initialise a maven project using the command `gauge init java_maven_selenium`

 > The problem is every time i reopen folder or vscode, all the selenium jars references gets removed automatically from .classpath file and i am not able to figure out what is causing it. Below is the structure of the .classpath file which it reverts back to.

This is an issue that will be fixed soon https://github.com/getgauge/gauge-vscode/issues/385 as a workaround please try using gauge+selenium+maven

For more help please reach out at https://spectrum.chat/gauge

**Comment by sriv** [comment] 2020-10-27 03:38
@manavghaigit as an alternative, you can copy the jar to the `libs` directory in the project root.

Or if you have any directory, you can specify [`GAUGE_ADDITIONAL_LIBS`](https://docs.gauge.org/configuration.html?os=windows&language=java&ide=vscode#java-properties-6) to point to the custom jar.
