### ISSUE TITLE
Unable to add image or link in .spec

### ISSUE THREAD

**Issue by mproboeuf** [getgauge/gauge#251] opened 2015-11-16 15:01 UTC
Hi,

I'm using Gauge 0.2.1 with html-report 1.1.0 on Windows
I want to add image and link through markdown syntax in my spec file, as described in http://getgauge.io/documentation/user/current/cheat_sheet/README.html#images

But, i wasn't able to do it, image and link are not interpreted in my report.
Is it actually supported ? Could you please provide me an example of how using it in my spec file ?

Thanks.
Matthieu.

**Comment by apoorvam** [comment] 2015-11-16 16:34
@mproboeuf 
The documentation that you have pointed out says it correct. An image is added as:
 `![Specification](spec.png)` 
where the current spec file and `spec.png` are files in same directory. Please make sure that the path to image file is relative to current directory. 

A link is added as: 
`This is [an example](http://getgauge.io "Title") inline link.`

However, these are not shown in Execution reports yet. There is an issue for this already [here](https://github.com/getgauge/html-report/issues/19). 

But these can be seen in the Html preview tab, if you are using Intellij IDE (This tab is shown at the bottom of editor). This preview shows up the images and links as well. 
Since specs are written in markdown, this can be converted to html using any markdown to html convertors. With this, the images and links should be shown in html too.

**Comment by Thunderforge** [comment] 2015-11-16 19:47
@apoorvam I don't see any HTML Preview tab at the bottom of Intellij IDEA, nor anywhere else in the app. Could you please clarify where to find that?

**Comment by apoorvam** [comment] 2015-11-17 08:15
@mproboeuf @Thunderforge Please refer documentation [here](http://getgauge.io/documentation/user/current/ide_support/other_usability_features.html#6-html-preview-tab) to check on how to find HTML preview tab.

**Comment by Thunderforge** [comment] 2015-11-17 15:41
@apoorvam Strange, I don't see a tab there. Is there some option to show it that has been turned off for me?

**Comment by apoorvam** [comment] 2015-11-19 06:15
@Thunderforge This is really strange. Are you on latest version of Gauge-IntelliJ plugin? Let us know the version of IntelliJ IDE you are using, so that we can reproduce. 

@mproboeuf Are you also not able to see `HTML Preview` tab in a spec file?

**Comment by Thunderforge** [comment] 2015-11-19 15:44
I am running the latest version of Intellij IDEA (15.0.1) and the latest version of the Gauge plugin (0.0.14). If it matters, this was a Gauge project created from the Twist to Gauge migration.

**Comment by mahendrakariya** [comment] 2015-12-01 08:58
@Thunderforge We just tested on IntelliJ IDEA v15.0.1 (Ultimate edition) on Mac with Gauge IntelliJ plugin version 0.0.15. We are able to see the HTML Preview tab for the spec files that we open.

Could you please confirm that [editor tabs are enabled](https://www.jetbrains.com/idea/help/configuring-behavior-of-the-editor-tabs.html)?

**Comment by Thunderforge** [comment] 2015-12-02 20:27
Editor tabs do appear since upgrading to Gauge Intellij plugin 0.0.15.

**Comment by apoorvam** [comment] 2015-12-08 05:16
Great!
We are closing this issue for now. Please feel free to re-open it if you face this issue further.

**Closed by apoorvam** 2015-12-08 05:16 UTC
Labels: response needed
