### ISSUE TITLE
Concept step implementation not found

### ISSUE THREAD

**Issue by pvskarps** [getgauge/gauge#320] opened 2016-04-06 21:10 UTC
We are seeing a problem with Gauge 0.4.0 when executing specs based off tags that are at a different folder level than concepts that the specs contain.  For instance if the specs are contained in specs\automated and the concepts are contained in specs\concepts.  The execution will error saying Step implementation not found.  Downgrading to Gauge .3.2 fixes the problem.  Interestingly the reference to the concept's step implementation works fine inside of Intellij.  

### Expected behavior
spec and scenarios execute without Gauge errors

### Actual behavior
spec execution skipped due to
validation errors saying Step implementation not found for each concept in the scenario

### Steps to reproduce
1. Create a spec in a subfolder (specs\automated\specInSubfolder.spec) with tags (tag1, tag2) specified
2. Add a scenario with a concept (create a concept and place it in specs\concepts\concept1.cpt) to the spec
3. Execute the spec based off the tags used.  For instance "gauge specs\automated --tags "tag1 & tag2""
4. You should see the issue.
5. Interestingly if you execute the spec by specifying the full spec name without using tags it will run fine. "gauge specs\automated\specInSubfolder.spec"

I have attached an Intellij (Created with Intellij 2016.1.1) project that hopefully will show the issue.

### Gauge version
Gauge version: 0.4.0

Plugins
-------
html-report (2.1.0)
java (0.3.4)

[gaugeIssue.zip](https://github.com/getgauge/gauge/files/207355/gaugeIssue.zip)

**Comment by apoorvam** [comment] 2016-04-07 06:35
@pvskarps Thank you for the clear explanation of the issue along with steps. It's great!

This was happening because `gauge specs/automated/foo.spec` didn't parse the concept files present in specs dir. This issue is now fixed.

**Closed** 2016-04-07 06:34 UTC
Labels: bug

**Comment by sguptatw** [comment] 2016-04-07 11:58
"Scenario Tagged Expression In Subfolder Execution" is the functional test in regression
