### ISSUE TITLE
Unable to run specs with dotnet plugin

### ISSUE THREAD

**Issue by bugraoguzhanyildiz** [getgauge/gauge#1571] opened 2020-02-01 09:22 UTC
### Expected behavior
gauge run specs/ should work with dotnet plugin
```
SDK Version: 3.1.101
```
Plugins
```
dotnet (0.1.2)
```
```
html-report (4.0.8)
```
```
screenshot (0.0.1)
```

### Actual behavior
Throws exception below;
Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:52553] cause: EOF
Successfully generated html-report to => ../reports/html-report/index.html
System.IO.FileLoadException: Could not load file or assembly 'Gauge.CSharp.Lib, Version=0.7.6.0, Culture=neutral, PublicKeyToken=3f92af01a0ea350e'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Gauge.Dotnet.Wrappers.AssemblyWrapper.LoadFrom(String location) in /Users/vivek/Documents/Parmanu/pipelines/dotnet-package/src/Wrappers/AssemblyWrapper.cs:line 43
   at Gauge.Dotnet.AssemblyLoader.ScanAndLoad(String path) in /Users/vivek/Documents/Parmanu/pipelines/dotnet-package/src/AssemblyLoader.cs:line 125
   at Gauge.Dotnet.AssemblyLoader..ctor(IAssemblyWrapper assemblyWrapper, IEnumerable`1 assemblyLocations, IReflectionWrapper reflectionWrapper) in /Users/vivek/Documents/Parmanu/pipelines/dotnet-package/src/AssemblyLoader.cs:line 42
   at Gauge.Dotnet.MessageProcessorFactory.GetProcessor(MessageType messageType, Boolean scan) in /Users/vivek/Documents/Parmanu/pipelines/dotnet-package/src/MessageProcessorFactory.cs:line 50
   at Gauge.Dotnet.GaugeListener.PollForMessages() in /Users/vivek/Documents/Parmanu/pipelines/dotnet-package/src/GaugeListener.cs:line 54

### Gauge version
```
Gauge version: 1.0.6
```

**Comment by sriv** [comment] 2020-02-03 05:47
I can replicate this issue with `gauge v1.0.6` and `gauge-dotnet v0.1.2`. The cause of this is that we did not sign assemblies on Linux (it was a limitation with dotnet version at that time)

And when we moved to a linux based build, the assemblies did not get signed anymore. 

This should be fixed in the upcoming release, which will follow the next Gauge release.

**Comment by Debashis9012** [comment] 2020-02-20 06:21
This issue has been verified and found fixed. 
Tested version:
```
Gauge version: 1.0.7
Commit Hash: f6f30bce

Plugins
-------
dotnet (0.1.3)
html-report (4.0.9)

```

**Closed by Debashis9012** 2020-02-20 06:21 UTC
Labels: bug
