### ISSUE TITLE
Add support for scenario breakpoints/manual steps

### ISSUE THREAD

**Issue by cstanush** [getgauge/gauge#308] opened 2016-03-09 16:47 UTC
### Expected behavior
Twist had the ability to have an unimplemented step that would stop the scenario execution and allow the user to do a manual task or review code. Please add this feature to Gauge.

### Gauge version
Gauge version: 0.3.2
![twistmanualstep](https://cloud.githubusercontent.com/assets/17650182/13642957/42c17b4c-e5e4-11e5-9c2f-77e310981c5a.PNG)

**Comment by cstanush** [comment] 2016-03-09 16:49
![twistmanualsteppopup](https://cloud.githubusercontent.com/assets/17650182/13643040/8daa255a-e5e4-11e5-96d8-6c16f2da8d92.PNG)

**Comment by mahendrakariya** [comment] 2016-03-09 17:33
This seems to be a duplicate of #50. There is some interesting discussion on that issue around this feature.

**Comment by kashishm** [comment] 2016-04-18 07:43
Let's track this issue at #50.

**Closed by kashishm** 2016-04-18 07:43 UTC
Labels: duplicate, new feature
