### ISSUE TITLE
No way to define separate table-driven execution values

### ISSUE THREAD

**Issue by harinee** [getgauge/gauge#312] opened 2016-03-21 13:58 UTC
### Expected behavior
There should be way to define data in table-driven execution at scenario level.
I may not necessarily use the same data all through the specification.

### Actual behavior
The only way to define data for table-driven execution is from the spec level. So I have to define a spec for every scenario I want to test with different combinations of data.

### Steps to reproduce
http://getgauge.io/documentation/user/current/execution/table_driven_execution.html

### Gauge version
Gauge version: 0.3.0

**Comment by mahendrakariya** [comment] 2016-03-21 14:01
This seems to be a duplicate of #111.

**Comment by kashishm** [comment] 2016-04-18 07:42
We will track this at #111.

**Closed by kashishm** 2016-04-18 07:42 UTC
Labels: duplicate
