### ISSUE TITLE
Fail Jenkins job build without generating html report

### ISSUE THREAD

**Issue by bzarnaudov** [getgauge/gauge#2305] opened 2022-11-08 19:22 UTC
I have Jenkins job which has around 3000 scenarios and problem is that if the job continues more than 50 minutes it fails with : 

[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.5.0:execute (parallelTest) on project *******-api-tests: Gauge Specs execution failed. null: GaugeExecutionFailedException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.5.0:execute (parallelTest) on project *******-api-tests: Gauge Specs execution failed. null
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
Caused by: org.apache.maven.plugin.MojoFailureException: Gauge Specs execution failed. null
    at com.thoughtworks.gauge.maven.GaugeExecutionMojo.execute (GaugeExecutionMojo.java:133)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
Caused by: com.thoughtworks.gauge.maven.exception.GaugeExecutionFailedException
    at com.thoughtworks.gauge.maven.GaugeCommand.execute (GaugeCommand.java:37)
    at com.thoughtworks.gauge.maven.GaugeExecutionMojo.execute (GaugeExecutionMojo.java:131)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)

and it didn't generate report. I tried to change gauge-maven-plugin version with 1.4.2 , 1.4.3 and it is the same error.

I tried to run with -n=100 so job to be fast and it gave this error : 
![image](https://user-images.githubusercontent.com/11505900/200654752-83285cb5-9c77-4322-9004-c3f795771f01.png)

When I run the tests locally this problem doesn't appear and it generate the html report.
It may be some resource problem? Memory, cpu of the Jenkins pod ?
The report is very huge, maybe html report plugin crashes?

Do you have any idea from what this is happening?

Gauge version: 1.4.3
Plugins
-------
html-report (4.1.4)
java (0.9.1)
screenshot (0.1.0)
spectacle (0.1.4)
```

**Comment by bzarnaudov** [comment] 2022-11-15 18:55
help please? :(

**Comment by zabil** [comment] 2022-11-16 10:20
Does your html report have images and have screenshot? (other than automatic screenshots on failure)

**Comment by bzarnaudov** [comment] 2022-11-17 10:40
No, I turned off screenshots, because the tests are only backend calls
here are my config files : 

default.properties

# default.properties
# properties set here will be available to the test execution as environment variables

# sample_key = sample_value

# The path to the gauge reports directory. Should be either relative to the project directory or an absolute path
gauge_reports_dir = reports

# Set as false if gauge reports should not be overwritten on each execution. A new time-stamped directory will be created on each execution.
overwrite_reports = true

# Set to false to disable screenshots on failure in reports.
screenshot_on_failure = false

# The path to the gauge logs directory. Should be either relative to the project directory or an absolute path
logs_directory = logs

# Set to true to use multithreading for parallel execution
enable_multithreading = false

# Possible values for this property are 'suite', 'spec' or 'scenario'.
# 'scenario' clears the objects after the execution of each scenario, new objects are created for next execution.
gauge_clear_state_level = scenario

# The path the gauge specifications directory. Takes a comma separated list of specification files/directories.
gauge_specs_dir = specs

# The default delimiter used read csv files.
csv_delimiter = ,

# Allows steps to be written in multiline
allow_multiline_step = false

# Sets the timeout in milliseconds for Gauge while
# connecting to plugins (except language runner plugins).
plugin_connection_timeout = 80000

# Sets the timeout in milliseconds for a plugin to stop
# after a kill message has been sent.
plugin_kill_timeout = 80000

# Sets the timeout in milliseconds for Gauge while
# connecting to the language runner.
runner_connection_timeout = 80000

# Sets the timeout in milliseconds for requests from the
# language runner to Gauge.
# If the size of the Gauge project is too big, Gauge might time out before the
# language runner returns the response message.
runner_request_timeout = 80000


config.properties which I run 

http_report_logging_enabled=true
enable_multithreading=true
gauge_data_dir = data/stg/


this is jenkins file : 

pipeline {
    agent {
        kubernetes {
            inheritFrom 'default'
            label 'newman'
            yaml '''
              spec:
                containers:
                  - name: "java"
                    command:
                      - "sleep"
                    args:
                      - "99d"
                    resources:
                      requests:
                        cpu: 1
                        memory: 1Gi
                      limits:
                        cpu: 2
                        memory: 2Gi
                    image: "nexo.pe.jfrog.io/devops-docker/amazoncorretto:17.0.1-004"
                    imagePullPolicy: "IfNotPresent"
            '''
        }
    }

    triggers {
        cron('H 21 * * *')
    }

    environment {
        JFROG_CREDENTIALS = credentials('jenkins-jfrog')
    }

    stages {
        stage("Build") {
            steps {
                container('java') {
                    sh './mvnw clean install -DskipTests'
                }
            }
        }
        stage("Setup Gauge"){
            steps {
                container('java') {
                    sh 'yum -y install curl unzip'
                    sh 'curl -SsL https://downloads.gauge.org/stable | sh'
                    sh 'gauge install java'
                }
            }
        }
        stage("Execute tests") {
            steps {
                container('java') {
                    sh './mvnw test -Denv="stg"'
                }
            }
        }
    }
    post {
        always {
            script {
                if (fileExists('reports')) {
                    archiveArtifacts artifacts: 'reports/**/*.*'

                    publishHTML([
                                reportDir: 'reports',
                                reportFiles: 'html-report/index.html',
                                reportName: 'Fincore-API-Tests-Result',
                                allowMissing: true,
                                alwaysLinkToLastBuild: true,
                                keepAll: true])
                }
            }
        }
    }
}

**Comment by sriv** [comment] 2022-11-17 11:28
I believe the problem is because html-report expects a max result size of 1GB (https://github.com/getgauge/html-report/blob/master/main.go#L61)

Whereas this project is sending 1.72GB (1847395418 bytes) as per the error message.

With 3000 odd specs it seems a bit high, and I have not seen it grow this big unless there's screenshots involved (which are muled over as base64 string). So this is quite strange.

**Comment by bzarnaudov** [comment] 2022-11-18 06:47
This 1gb is max size of all hmtl- files or for separate spec html?

There is no screenshots involved here. There is many response body logs.

**Comment by sriv** [comment] 2022-11-18 07:40
> This 1gb is max size of all hmtl- files or for separate spec html?

This is actually the size of the message that is passed from gauge to the report plugin. It could be because of the response body logs.

I'll try to make this configurable so that you can set a higher limit (need to get to my personal computer)

**Comment by bzarnaudov** [comment] 2022-11-18 07:49
What is in this message? I see Gauge generate html file for every spec and every html size depends of the scenarios count in the spec.

This will be good to have such a parameter to set for big data testing. For now I will set scenarios to be less count, so the size of htmls will be lower. Thank you very much. How can I inform when this config will be ready, if you make it? To check new releases notes?

**Comment by sriv** [comment] 2022-11-19 05:52
The message contains details of the execution including result and stacktrace etc, but in a binary format. The plugins are responsible for consuming it.

I have raised a PR -> https://github.com/getgauge/html-report/pull/291, post which there should be a new html-report version released.

**Comment by bzarnaudov** [comment] 2022-11-21 21:41
Okay thank you very much.

**Comment by sriv** [comment] 2022-11-23 04:12
html-report v4.2.0 is out and you should be able to set `gauge_max_message_size` in MBs in your properties file or env variable. Please set this to a value acceptable to your project.

**Comment by sriv** [comment] 2022-11-30 04:35
I am closing this issue against #291.

**Closed by sriv** 2022-11-30 04:35 UTC
