### ISSUE TITLE
Gauge+Taiko takes time to performing any actions against the browser

### ISSUE THREAD

**Issue by varayal** [getgauge/gauge#1255] opened 2018-11-26 22:04 UTC
### Expected behavior

Gauge should run the taiko instructions/commands taking the similar time that running the script using taiko standalone.

### Actual behavior

My script works as expected by running it using taiko. 

```
taiko script.js
```

After integrating the same script with Gauge. I noticed each command/instructions that taiko sends against chromium takes time (more than expected). Finally after the 3rd step I got the following error on the console

```
        Error Message: Error: Timed out
        Stacktrace:
        Error: Timed out
            at Timeout.<anonymous> (/Users/victor.araya/.gauge/plugins/js/2.3.2/src/test.js:43:23)
            at ontimeout (timers.js:436:11)
            at tryOnTimeout (timers.js:300:5)
            at listOnTimeout (timers.js:263:5)
            at Timer.processTimers (timers.js:223:10)
```

### Steps to reproduce
1. Create the script by using taiko
2. Integrate the script with gauge

### Gauge version

```
Gauge version: 1.0.3

Plugins
-------
html-report (4.0.6)
js (2.3.2)
ruby (0.5.1)
screenshot (0.0.1)
```

**Comment by varayal** [comment] 2018-11-26 23:02
I noticed that gauge takes 25-sec approx to send the next instruction to chromium.

Why does gauge take that time?

**Comment by NivedhaSenthil** [comment] 2018-11-27 08:20
shouldn't be happening ...can you share a sample to reproduce above scenario ?

**Comment by varayal** [comment] 2018-11-29 21:49
After disabling ```waitForNavigation``` the issue was fixed.

**Comment by varayal** [comment] 2018-11-29 21:49
please proceed to close this issue.

**Comment by Apoorva-GA** [comment] 2018-11-30 03:15
Thanks for the update @varayal. 
Closing the issue for now.

**Closed by Apoorva-GA** 2018-11-30 03:15 UTC
Labels: community

**Comment by NivedhaSenthil** [comment] 2018-11-30 05:00
wondering why `waitForNavigation` is causing Timeout in gauge...default timeout in taiko for actions is 15secs whereas Timeout in gauge is 60secs. Taiko should have timed out way before and proceeded to next action, trying to understand in which scenario this can happen. Any sample would be really helpful.

**Comment by Apoorva-GA** [comment] 2018-11-30 05:44
@NivedhaSenthil May be we can track it as a different issue, if that needs from verification.

**Comment by boomi243** [comment] 2019-01-31 21:18
Hi All, I am getting Timed Out Error while running gauge taiko automated scripts from GoCD server
Failed Step: Goto AU main page
Specification: specs\createNewAttributionFromCSV.spec:10
Error Message: Error: Timed out
Stacktrace:
Error: Timed out
at Timeout.<anonymous> (C:\Windows\system32\config\systemprofile\AppData\Roaming\gauge\plugins\js\2.3.4\src\test.js:43:23)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
This is working fine when we run in local machine.

**Comment by NivedhaSenthil** [comment] 2019-02-01 03:41
@boomi243 can you please give some more details about your environment like os, gauge, gauge-js and taiko versions ?

**Comment by Yashas0796** [comment] 2019-07-23 07:17
I have installed gauge and taiko in my system. But am not able run the scripts in gauge due to timeout Error

**Comment by Yashas0796** [comment] 2019-07-23 07:19
Error:
  Error Message: Error: Timed out
  Stacktrace:
  Error: Timed out
      at Timeout.<anonymous> (C:\Users\yashaswini.b\AppData\Roaming\gauge\plugins\js\2.3.5\src\test.js:43:23)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)

**Comment by cristianmercado19** [comment] 2019-09-27 14:44
After follow the installation guide, I have faced same issue when I run `gauge run specs`

```
> gauge-taiko-template@0.0.1 test e:\taiko-eg
> gauge run specs/

(node:11944) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead

  Error Message: Error: Timed out
  Stacktrace:
  Error: Timed out
      at Timeout.<anonymous> (C:\Users\MERCADOCX\AppData\Roaming\gauge\plugins\js\2.3.5\src\test.js:43:23)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)

  Error Message: Error: WebSocket is not open: readyState 3 (CLOSED)
  Stacktrace:
  Error: WebSocket is not open: readyState 3 (CLOSED)
      at WebSocket.send (node_modules\ws\lib\websocket.js:329:19)
      at Chrome._enqueueCommand (node_modules\chrome-remote-interface\lib\chrome.js:277:18)
      at Promise (node_modules\chrome-remote-interface\lib\chrome.js:85:22)
      at new Promise (<anonymous>)
      at Chrome.send (node_modules\chrome-remote-interface\lib\chrome.js:84:20)
      at Object.handler [as close] (node_modules\chrome-remote-interface\lib\api.js:32:23)
      at _closeBrowser (node_modules\taiko\lib\taiko.js:223:20)
Successfully generated html-report to => e:\taiko-eg\reports\html-report\index.html
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped
```

Workaround not final solution:
Edit [project-folder]\env\default\headless.properties
change default value false to true
`headless_chrome = true`

**Comment by tester-mind** [comment] 2023-04-14 12:13
I am also facing a similar issue. The workaround `headless_chrome = true ` you mentioned is not working. It fails even in headless mode.
