### ISSUE TITLE
Gauge throwing "Duplicate step implementation" on all steps

### ISSUE THREAD

**Issue by musicbyjing** [getgauge/gauge#1356] opened 2019-02-27 15:52 UTC
### Expected behavior
Tests should run properly

### Actual behavior
Gauge throws "Duplicate step implementation" on _all_ steps

### Steps to reproduce
1. Use Maven to build project in VSCode
2. Put the step implementation file (in my case Java) in `src/main/java` (the ultimate goal is to have one file including a main method _and_ the step implementations, which will make packaging the .jar easier)
3. Set `gauge_custom_compile_dir = src/main/java/` in `env/default/java.properties`

### Gauge version
```
Gauge version: 1.0.4

Plugins
-------
html-report (4.0.6)
java (0.7.1)
screenshot (0.0.1)
xml-report (0.2.1)

```

**Comment by negiDharmendra** [comment] 2019-02-27 16:24
@musicbyjing Thanks for reporting the issue. 

We would need some information to investigate this issue. 

- Which OS you are using.
- Are you seeing this issue only in a particular project or in all the projects?
- Please share the LSP logs with us.

**Comment by musicbyjing** [comment] 2019-02-27 16:50
I'm using RHEL 7. This is the only project I have so I'm not sure. How do I get the LSP logs?

**Comment by negiDharmendra** [comment] 2019-02-27 17:02
@musicbyjing You can find the LSP logs inside `<gauge_project_directory/logs/>`

**Comment by musicbyjing** [comment] 2019-02-27 18:27
I'm not sure if I'm allowed to post that, but here's the error message if that helps:
`Exception in thread "main" org.reflections.ReflectionsException: Can't resolve member named verifySelected for class StepImplementation
	at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:94)
	at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
	at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:443)
	at com.thoughtworks.gauge.scan.StepsScanner.scan(StepsScanner.java:40)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:48)
	at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:105)
	at com.thoughtworks.gauge.GaugeRuntime.startGaugeServer(GaugeRuntime.java:73)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:51)
process /usr/bin/java with pid 27616 quit unexpectedly. exit status 1`

**Comment by ajoecker** [comment] 2019-02-28 05:56
is `verifySelected` public ?

btw - for gauge you do not need a main method

**Comment by musicbyjing** [comment] 2019-02-28 15:30
Yes, it's public. I'm aware of that but I'm trying to wrap it in a jar, so I basically have the main method calling `mvn gauge:execute`. I thought it might be a cause of this issue but I'm not sure.

**Comment by ajoecker** [comment] 2019-02-28 15:47
I would advice against that. I can not think of a use case for doing so, especially as this might cause side effects/problems with classpath and files. 
Where do you put the specs, where the environmental information etc.... calling a command line from Java is always troubling with classpath etc.
So do you a favor and try it with out the wrapping. 


Gesendet von Yahoo Mail für iPhone


Am Donnerstag, Februar 28, 2019, 4:30 PM schrieb Jing Liu <notifications@github.com>:


Yes, it's public. I'm aware of that but I'm trying to wrap it in a jar, so I basically have the main method calling mvn gauge:execute. I thought it might be a cause of this issue but I'm not sure.

**Comment by nehashri** [comment] 2019-03-07 06:52
This issue seems to be a duplicate of https://github.com/getgauge/gauge-java/issues/221. There is fix that is pushed to the Gauge nightly >= 7-3-2019, please see if this resolves your issue. To install nightly version of gauge-java refer [here](https://github.com/getgauge/gauge-java#nightly-installation).

**Comment by musicbyjing** [comment] 2019-03-08 15:12
@ajoecker I'm trying to run a Selenium test that implements Gauge from within a jar file. I don't see any other way to do it other than calling the command line from within Java. It's actually working on Linux, but Windows is another story. If you have any alternative suggestions to accomplish this I would be very grateful.

@nehashri The issue seems to be gone, thank you!

**Closed** 2019-03-08 15:12 UTC
Labels: community

**Comment by ajoecker** [comment] 2019-03-08 15:32
@musicbyjing I have the same setup, having some gauge step implementations in a jar to be used in selenium tests, to implement common behavior between selenium projects.
I use maven-java projects and there it is simply to include the jar with the common step implementation as dependency, then I can have a "normal" gauge project, that can reuse the dependency steps, as also their own.
No need to call any command line or whatsoever, as long as the jar with the common functionality is in the classpath
