### ISSUE TITLE
Running spec multiple times

### ISSUE THREAD

**Issue by SreejithShenoi** [getgauge/gauge#820] opened 2017-09-23 13:06 UTC
Is there a way in gauge to run a single spec/ multiple spec/directories for multiple iterations with a single command?
eg : 
gauge run specs --iterations 2
gauge run specs/spec1.spec -- iterations 3
gauge run specs/spec1.spec specs/spec2.spec --iterations 10

**Comment by zabil** [comment] 2017-09-25 02:30
Can you describe why you want this feature and its use cases?

You can wrap the execution around a script to run it multiple times. This way, you see the reports for all the runs (if the [preserve](https://docs.getgauge.io/configuration.html#default-properties-5) reporting option is on).

**Comment by SreejithShenoi** [comment] 2017-09-25 17:30
Thanks for the prompt response.

One use case could be run a spec multiple times to see the stability of the feature. Or it could be even running a scenario multiple times to check the stability or to support reproduction of defects(especially sometimes issues)

We tried calling gauge.exe from our application wrapper based on number of iterations required. Probelm with that would be the following.

1. Each time Gauge run <specname> is called, execution hooks like BeforeSuite() would be called. We do pre conditions required for test execution in BeforeSuite() and do clean up in AfterSuite(). So if we want to run a spec/scenario 100 times we would need to perform setup and clean up 100 times, where as it is required only once. In our case suite setup is a time taking process, so it adds to the test execution time drastically.

2. With overwrite_reports = false, we would get report for all executions, but there would be no consolidated report where we can get the complete result of all iterations. Going through each individual report would be a cumbersome process.

So if Gauge exe can take iterations as parameter and this could be handled internally, then it would be great.

The above mentioned points are based on our current understanding on gauge. Please let us know if there is a way to get around it.

**Comment by zabil** [comment] 2017-09-26 06:02
@SreejithShenoi 

Makes sense, to debug failures. 

We'll leave this open to see if other people are interested in this feature. We are working on a lot of other features and this may not be prioritized. 

We'll help anyone who wants to pick this up.

**Comment by Apnikolak** [comment] 2018-07-03 16:04
Seems similar to what I asked in #1092 @zabil

**Comment by ajoecker** [comment] 2018-07-04 00:07
> One use case could be run a spec multiple times to see the stability of the feature. Or it could be even running a scenario multiple times to check the stability or to support reproduction of defects(especially sometimes issues)
I still do not get that point from a tester point of view. Do you pass a feature when it succeeds 5 out of 8 times ? or 9 out of 10 ? What shall this stability mean ? If your test show that a feature is not stable, then either fix the feature or the test.
Also regarding reproducing a defect - if it is a clear case, then now iterations are required. And even if this is one of those rare cases happens rarely, how shall iterations help here ? Crossing fingers that when running it 10 times, it will break eventually - how shall this help tracking down the issue ?

Sorry, I can not think of any case where an iteration feature makes sense

**Comment by sriv** [comment] 2018-07-04 02:07
I [commented](https://github.com/getgauge/gauge/issues/1092#issuecomment-402340597) on #1092, but for convenience's sake, here is my view on this:

Gauge does not possess any intelligence to determine if the current failure is caused by a genuine regression/mismatched expectation or if it is an intermittent error.

For me the key thing is: if I am a user of the app being tested, would I be ok to retry X times for the feature to work? Most likely not. If that is true for an actual user, I think the same (if not stricter norms) should be expected from the test as well.

> aside 1: if you/anyone have ideas on how to infer a cause of a failure (beyond just stacktraces/error messages) that would be a very interesting feature to build out.

> aside 2: At a meta level, this should probably be something that should be derived over a period of run (perhaps with multiple environments). e.x. from a CI run history, if there is some aggregation of failures, it can lead some insights into fragile/stable features of the application.

**Comment by zabil** [comment] 2019-04-30 08:57
Closing this as it won't be implemented.
Part of this will be solved via https://github.com/getgauge/gauge/issues/1375
For usage refer https://docs.gauge.org/latest/execution.html#re-run-flaky-tests-with-max-retry

**Closed by zabil** 2019-04-30 08:57 UTC

**Comment by aakilb** [comment] 2021-12-06 16:15
How can I run a spec file on loop a fixed number of times?

**Comment by zabil** [comment] 2021-12-07 14:18
> How can I run a spec file on loop a fixed number of times?

You could write a simple script the runs `gauge run` in a loop for example to run a spec 5 times bash

```
for i in {1..5}; do gauge run specs/example.spec; done
```

**Comment by aakilb** [comment] 2021-12-07 20:45
> > How can I run a spec file on loop a fixed number of times?
> 
> You could write a simple script the runs `gauge run` in a loop for example to run a spec 5 times bash
> 
> ```
> for i in {1..5}; do gauge run specs/example.spec; done
> ```

Thank you zabil. I did what you said and that part is working now. I have one question. How can I combine all the HTML reports that get generated into a single HTML report that shows how many specs passed and how many failed?

Thanks again.
