### ISSUE TITLE
Unable to debug java maven projects

### ISSUE THREAD

**Issue by ovixeu** [getgauge/gauge#1754] opened 2020-09-14 08:00 UTC
UPD: after a lot of experiments, looks like debug is failing due to java-plugin version 0.7.8 and tested also with 0.7.9
Using gauge runner 1.1.4 with java-plugin 0.7.7 debug works fine.

Using intelliJ Idea 2020.1 with gauge-plugin version 0.3.21

Reproducing steps:

1. Init a new project using command 'gauge init java_maven'
2. mvn clean install
3. Tring to debug a step get the error:

Testing started at 10:43 AM ...
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console D:/Gauge/template-project/specs/example.spec

Runner Ready for Debugging
Listening for transport dt_socket at address: 57392
Error ----------------------------------

[Gauge]
Failed to start gauge API: Timed out connecting to java

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	windows, 1.1.4, c982558
	html-report (4.0.12), java (0.7.9), json-report (0.3.5), screenshot (0.0.1), spectacle (0.1.4)

Process finished with exit code 1

gauge.log
-----------
Runner Ready for Debugging
14-09-2020 10:53:21.512 [java] [DEBUG] running - C:\Program Files\Java\jdk-14.0.1\bin\java.exe [-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=57656,timeout=25000 -Dfile.encoding=UTF-8 com.thoughtworks.gauge.GaugeRuntime --start]
14-09-2020 10:53:21.512 [java] [DEBUG] stdout/stderr is logged to logs\12988-java.exe.out
14-09-2020 10:53:22.289 [java] [INFO] Listening for transport dt_socket at address: 57656
14-09-2020 10:53:44.326 [Gauge] [CRITICAL] Failed to start gauge API: Timed out connecting to java

12988-java.exe.out
---------------------
Listening for transport dt_socket at address: 57656

$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by NivedhaSenthil** [comment] 2020-09-25 05:00
Closing as this is a duplicate of https://github.com/getgauge/gauge-java/issues/501

**Closed by NivedhaSenthil** 2020-09-25 05:00 UTC
