### ISSUE TITLE
gauge screenshot should user headless drivers' inbuilt mechanism

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#107] opened 2015-03-05 05:59 UTC
Expose a hook to capture screenshot at language runner level, this should allow users to use mechanisms like Capybara's [`save_screenshot`](http://www.rubydoc.info/gems/capybara/2.4.4/Capybara/Session#save_screenshot-instance_method)

**Comment by prateekbaheti** [comment] 2015-03-05 06:30
duplicate of #9

**Closed** 2015-03-05 06:42 UTC
