### ISSUE TITLE
couldn't get the SuiteStore value in afterSuite hooks

### ISSUE THREAD

**Issue by zhangty0101** [getgauge/gauge#1693] opened 2020-07-16 10:26 UTC
![image](https://user-images.githubusercontent.com/38073195/87661211-d15e6b00-c792-11ea-9a95-a7d5781bff50.png)
![image](https://user-images.githubusercontent.com/38073195/87661253-e1764a80-c792-11ea-8112-758b1834ea08.png)

 
I think the SuiteStore value should be clear after afterSuite hook executed rather than before

**Comment by NivedhaSenthil** [comment] 2020-07-17 08:31
Duplicate of https://github.com/getgauge/gauge-js/issues/227. Please follow the tagged issue for progress.

**Closed by NivedhaSenthil** 2020-07-17 08:31 UTC
