### ISSUE TITLE
Support newline in step text

### ISSUE THREAD

**Issue by falkoschumann** [getgauge/gauge#265] opened 2015-12-02 14:58 UTC
When I insert a newline into long step text, Gauge use only the first line as step definition and ignore the second line.

Example:

```
* Step with a long
  line.
```

Gauge use only "Step with a long" as step definition and ignore "line."

I use Gauge with the Java plugin.

**Comment by sriv** [comment] 2015-12-02 16:02
This is by design, Gauge's grammar expects a step text to begin with an asterix (*) and end with a Newline. 

Would having a single line text, that can be word-wrapped in your editor be an option worth considering?

If Gauge has to support this, One way would be to introduce a way to escape newline in Gauge. Something like this:

```
* Step with a very very long line \
  that flows into two lines
```

Thoughts?

**Comment by falkoschumann** [comment] 2015-12-02 18:34
Soft wrap does not intend the wrapped line. It's only a small optical lack for printing as plain text for customer review. Specifications are written in Markdown so I expected the newline behavior of Markdown:

>To make lists look nice, you can wrap items with hanging indents [1]

When I write Markdown, escape the newline feels not good for me. Export or print the existing HTML preview of specification in IntelliJ would be a alternative to using plain text for communicating with customers. For the moment soft wrap is O.k.

[1]: https://daringfireball.net/projects/markdown/syntax#list

**Comment by Thunderforge** [comment] 2015-12-02 21:28
To clarifying what @falkoschumann is saying, the issue is that Gauge handles line breaks differently [than standard Markdown does](http://daringfireball.net/projects/markdown/syntax#p). In standard Markdown, a single break return after a list item is rendered as follows:

**Markdown:**

    * Asterisk
    No asterisk
    * Asterisk

**GitHub Render:**

* Asterisk
No asterisk
* Asterisk

**Gauge HTML Preview Render:**

*This renders it as though it had an intentional `<br/>` in it.*

![image](https://cloud.githubusercontent.com/assets/6200170/11544610/6e6b5d04-9908-11e5-9016-bd3df1689db0.png)

This is not how Gauge behaves. Instead it treats `No asterisk` as a comment distinct from the line above it.

Moreover, Gauge's HTML Preview tab (in IDEA) renders it as though it had an intentional `<br/>` in it:

This is the issue: Gauge doesn't reflect standard Markdown:

-------

As for a solution, I don't like the idea of adding a `\` to the end of the line, as that just makes Gauge deviate further from standard Markdown. An ideal solution would be to just require comments to be outside of a list. Not only is this proper Markdown, but it already renders properly in Gauge HTML Preview:

**Markdown:**

    * Step
    * Step
    
    Comment
    
    *Step

**GitHub Render:**

* Step
* Step

Comment

* Step

**Gauge HTML Preview Render:**

![image](https://cloud.githubusercontent.com/assets/6200170/11544700/e36d96da-9908-11e5-9353-53faa483ff62.png)


This would of course break existing specs that have comments as part of the list. However, I think it is best in the long run.

**Comment by sriv** [comment] 2015-12-03 06:01
Fair enough, I didn't realize that you could do that with lists in Markdown. Thanks for the tip!

@Thunderforge - I agree to your point on not deviating from markdown syntax.

marking this as an enhancement.

**Comment by florinalex24** [comment] 2018-07-18 08:21
Hi,
Any updates for this task?

**Comment by sriv** [comment] 2018-07-20 06:54
Hi @florinalex24 - nothing at the moment. But this may be one of the things we do in near future. 

We intend to have Gauge adhere to the markdown specification as much as we can.

**Comment by Achilles11** [comment] 2018-07-20 10:46
This would be really nice feature

**Comment by sriv** [comment] 2018-07-30 05:36
I am going to look at this, but wanted to validate a few things:

When there is a step (A):
```
* step text
more step text
```

1) The implementation shall have a `\n`, ex:

```
@Step("step text\nmore step text")
```

2) (1) means that the parsed step text will include line-breaks

3) (2) also means that, (A) is not the same as 

```
* step txt more step text
```

4) (2) contradicts with how inline tables' implementation work, but we can treat tables as a special case.

**Comment by zabil** [comment] 2018-07-30 06:02
Can we ignore the new line in the step annotation. Multi-line support is 

For e.g

```
@Step("step text more step text")
```
a) Part of the Markdown spec
b) For readability

When the step text is reformatted for readability it must to not break the implementation. The user can choose to format the annotation independent of the step text for e.g

```
@Step("step text" + 
    " more step text")
```

**Comment by ajoecker** [comment] 2018-07-30 06:12
I would also vote against the newline in the annotation. It is more confusing and I guess changing the spec slighlty (newline at another location) would break the whole thing.

with that said

```
* a long step that has some more text
```

should be treated identically from spec, as also from the implementation as

```
* a long step that
has more text
```
in my eyes, as the latter is only a way of presenting the information in a better way and has no functional implications

**Comment by sriv** [comment] 2018-07-30 06:20
The only reason for me leaning towards preserving the newline is because markdown does so. Ex:

```
* a long step that
has more text
``` 
is rendered as 

![screenshot from 2018-07-30 11-49-35](https://user-images.githubusercontent.com/389148/43380411-b6bcab1a-93ee-11e8-80eb-03c800aa4b6f.png)

Stripping out the newline will cause the `<br/>` to be removed in the html report. Thoughts?

**Comment by zabil** [comment] 2018-07-30 06:30
The reports must preserve new line and convert it to `<br/>` i.e the step text in the specification.

**Comment by nehashri** [comment] 2018-07-30 06:34
I agree with @zabil on the annotation not having `\n`. The user must be able to format the step text irrespective of the annotation and vice versa.
I don't think the user will be able to decide if a step is multiline or not while in the implementation, so forcing the user to declare the new line in the annotation does not work.

Consider this,
```markdown
* "Gauge" has "3" vowels.
```
another implementation may be,
```markdown
* "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." has "45" vowels.
```
For readability sake, the user may want to split the latter implementation into two parts, but not the first.

So there should be a way to indicate that a step is a multi-line step in the Markdown. Gauge should consider all lines as potential multiline steps. 

For backward compatibility, we should probably enable this behaviour through a property.

**Comment by sriv** [comment] 2018-07-30 06:40
@nehashri - your second case falls into #175 I guess?

**Comment by nehashri** [comment] 2018-07-30 06:43
@sriv yes you are right. But I could also format that as such
```markdown
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." 
has "45" vowels.
```
Readability is better in this case.

**Comment by sriv** [comment] 2018-07-30 06:45
So taking into consideration, the reporting and the implementation needs, perhaps we can do something like this:

- `.spec` and `.cpt` files can have newline in step texts.
- implementations (step annotation) would replace the new line with a space, thus allowing 
```
* step text
with two lines
```
to have implementation `@Step("step text with two lines")`

- gauge will pass another field for `Step` say `RawStepText` that will contain the step text as authored, which shall be used to render the reports.

Does that sound good? 

[aside: in the interest of multiple timezones, I'll wait for some time to hear more thoughts, if any]

**Comment by ajoecker** [comment] 2018-07-30 06:57
how is this considered to be handled internally ? 
so the `getActualText` or `getParseText`, respectively. Will they contain the newline ?

**Comment by sriv** [comment] 2018-07-30 07:30
@ajoecker  I suppose [`actualText`](https://github.com/getgauge/gauge-proto/blob/master/spec.proto#L158) would carry the text stripped of the newline, and a new field `rawText` would contain the text with the newline.

I am tempted to keep `actualText` as it is, else there will be cascading changes. With it being as it is, the changes will be additive, and would cause minimal disruption.

**Comment by sguptatw** [comment] 2018-08-09 04:31
- What should be the behavior when `create a concept` action is called on a step with multiple lines?

**Comment by ajoecker** [comment] 2018-08-09 07:07
there also exist: https://github.com/getgauge/gauge/issues/953, which also talks about the titles - is this change also including the titles?

**Comment by zabil** [comment] 2018-08-09 08:14
This only fixes multi line in steps.

Markdown supports multi line headers in this format

```
Line 1
Line 2
====
```

Gauge parses `====` / `-----` syntax as specification/scenarios but only uses the last line. 
In the example above the specification name will be `Line 2` and `Line1` appears as a comment.

**Comment by sguptatw** [comment] 2018-08-10 06:26
Getting wrong diagnostics after this implementation.

**Closed** 2018-08-13 06:30 UTC
Labels: enhancement, parser, triage

**Comment by smathistad** [comment] 2018-09-05 16:15
I think this was a bad idea, or at the very least, a bad implementation method.  Our test suite has a LOT of specs that have comments before and after step names. Now all of these specs are being skipped because of `Step implementation not found` errors.

Now I will potentially have to edit several hundred specs just to make it work like it was before.  At least I can roll back to version v1.0.0 until I have time work on it.
