### ISSUE TITLE
Should give validation error if scenario name is empty

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#378] opened 2016-05-07 11:14 UTC
### Expected behavior
Should give validation error if scenario name is empty

### Actual behavior
Empty scenario gives no validation error

### Steps to reproduce
1. Create a spec file abc.spec
```
Something
=========

     |dynamic|
     |-------|
     |       |
Scenario Heading
----------------
* Step that takes a table1 <dynamic>
* static param "abc"
* static param "def"

----------------

* static param "ghi"
* static param "jkl"

```
2. Give the implementation
```
    @Step("Step that takes a table1 <dynamic>")
    public void implementation5(Object arg0) {

    }

    @Step("static param <gjkg>")
    public void implementation6(Object arg0) {

    }
```
3. gotot the console and run
```
gauge --validate specs/abc.spec
It says no error
```

But should get error as there is no scenario heading

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-06

Plugins
-------
html-report (2.1.1.nightly-2016-05-02)
java (0.4.0)
xml-report (0.1.2)
```

**Comment by sriv** [comment] 2016-05-26 12:03
Verified as fixed as of 26-May, please check with nightly >= 26-05-2016.

**Comment by sguptatw** [comment] 2016-05-31 10:15
Checked from the IDE as well. The issue exists.

**Comment by apoorvam** [comment] 2016-06-02 07:02
Duplicate of #403 . Closing this for now.

**Closed by apoorvam** 2016-06-02 07:02 UTC
Labels: ready, type: bug
