### ISSUE TITLE
Feature Request: Automate the 'gauge run -f' possibility

### ISSUE THREAD

**Issue by Apnikolak** [getgauge/gauge#1092] opened 2018-06-19 22:08 UTC
### Expected behavior

Currently at the end of suite, when gauge creates the '.gauge/failures.json' file I checked the 'failedItems' and if they exist, save them. Then I get the 'lastRunCmd.json' to get the arguments for the last run command. I am trying to have the test check if the failedItems exist, run 'xyz' spec with the same arguments passed in earlier.

This is similar to how 'gauge run -f' works, where it will re-run only the tests that failed, but I am trying to do this in the project itself, through automation, before it actually generates the html for the pipeline.

Is this currently possible to do? If not could it be a future upgrade? 

### Gauge version
Gauge 0.9.9

**Comment by zabil** [comment] 2018-06-20 08:27
@Apnikolak is this because you have a flaky test?

**Comment by Apnikolak** [comment] 2018-06-20 13:42
@zabil Yes, the tests that run overnight, sometimes will fail overnight and when we check them in the morning, they run locally just fine.

So I look through the logs/screenshots to check what might have happened, and sometimes it's a scenario where the step before clicked a drop-down to show more information, and it failed trying to verify the drop-down information, when it runs locally and passes, I'll re-run the stage that the test was on, and it will pass this time around because the drop-down actually displayed this time and it had the info to verify.

We tried to counteract this flaky-ness by adding implicit waits in the methods, so say you are doing anything by Id or by Css Selector, we also have in that method a waitForCssSelectorToBeClickable/Visible or a wait for spinner to be invisible for loads.

**Comment by zabil** [comment] 2018-07-03 08:58
Closing this issue as the best solution to this is fixing flaky tests.

**Closed by zabil** 2018-07-03 08:58 UTC

**Comment by Apnikolak** [comment] 2018-07-03 15:55
How can 1 fix flaky tests, when they error out to network issues/page loading due to network, etc. 

TestNG has a class file to set re-run attempts. I am trying to manually set this up myself, by -> AfterScenario, get ExecutionContext, check if failing. If true, call a class I named FailedTestConfiguration, in here it opens up cmd, cd to path of project, execute gauge run -f.

This is where I am currently at, but at the moment it send me in an endless loop of rerunning that failed spec.

So if you have any helpful advice on how to set this logic up, i'd greatly appreciate it. @zabil

**Comment by sriv** [comment] 2018-07-04 01:58
Hi @Apnikolak , you say

> This is where I am currently at, but at the moment it send me in an endless loop of rerunning that failed spec.

This is exactly the reason Gauge cannot help. Gauge can execute specs, and the implementation can determine if the instantaneous state of the application is acceptable or not.

Gauge does not possess any intelligence to determine if the current failure is caused by a genuine regression/mismatched expectation or if it is an intermittent error. (on that note, if you/anyone have ideas on how to infer this, that would be a very interesting feature to build out).

Please note that as a developer, it is very easy for me to build this in - we are talking about a loop with maximum iterations (similar to what is requested in #820). But I think this would just be a glorified timeout like implementation.

For me the key thing is: if I am a user of the app being tested, would I be ok to retry X times for the feature to work? Most likely not. If that is true for an actual user, I think the same (if not stricter norms) should be expected from the test as well.

I understand our responses may  not be useful to this issue, but I hope you can appreciate why we are reluctant! Cheers.
