### ISSUE TITLE
[Gauge 1.5.7][linux][json-report] Json and Xml report is not getting generated on report folder location.

### ISSUE THREAD

**Issue by manojTest** [getgauge/gauge#2456] opened 2024-01-29 11:48 UTC
**Describe the bug**
I have observed that Json and Xml report is not getting generated in report folder on circle-ci linux machine. I am seeing the issue after the gauge stable version from 1.5.6 -> 1.5.7.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. I am installing gauge using curl -SsL https://downloads.gauge.org/stable | sh
2. when the gauge stable version was https://github.com/getgauge/gauge/releases/download/v1.5.6/gauge-1.5.6-linux.x86_64.zip. The reports are generated properly in json-report folder.
3. However when the gauge stable version changed to  https://github.com/getgauge/gauge/releases/download/v1.5.7/gauge-1.5.7-linux.x86_64.zip. It stops generating json and xml report.

**Logs**

```
Run log with gauge 1.5.6 version.
Successfully generated xml-report to => /home/circleci/project/reports/xml-report
Successfully generated json-report to => /home/circleci/project/reports/json-report
Successfully generated html-report to => /home/circleci/project/reports/html-report/index.html

Run log with gauge 1.5.7 version only see html-report
Successfully generated html-report to => /home/circleci/project/reports/html-report/index.html
```

**Expected behavior**
All the three report html, xml and json report should get displayed.

**Comment by chadlwilson** [comment] 2024-01-29 15:15
Looks the same as https://github.com/getgauge/xml-report/issues/61 which has some more details. Presumably caused by https://github.com/getgauge/gauge/pull/2451 ?

**Comment by nvborisenko** [comment] 2024-01-31 20:02
The same for me,  I see:

```
 Unable to connect to plugin JSON Report 0.3.7. rpc error: code = Unimplemented desc = unknown method NotifyConceptExecutionStarting for service gauge.messages.Reporter
```

**Comment by chadlwilson** [comment] 2024-02-01 01:29
I think stay with `1.5.6` for now is the suggestion, until the relevant plugins are updated.

**Comment by manojTest** [comment] 2024-02-01 06:38
In that case, please update the stable version to 1.5.6 in gauge repository. (curl -SsL https://downloads.gauge.org/stable)

**Comment by chadlwilson** [comment] 2024-02-01 06:51
@manojTest Please see https://github.com/getgauge/gauge?tab=readme-ov-file#important-note and temper your expectations of maintainers. While the change made in a patch version # change is unfortunate, this version is otherwise stable if you only use `html-report` plugin.

**Comment by manojTest** [comment] 2024-02-01 07:13
@chadlwilson Thanks for the Important-note. I was not aware of the Gauge official sponsorship got ended 2021.  In that case, please provide me any alternate workaround to download the gauge 1.5.6 on the Cirecle-Ci virtual VM as I am aware of the (curl -SsL https://downloads.gauge.org/stable) command. We are using Json-report plugin for updating testcase in our Testcase management tool.

**Comment by chadlwilson** [comment] 2024-02-01 07:34
You could try `curl -SsL https://downloads.gauge.org/stable | sh -s -- --version=v1.5.6` but I haven't personally tried it.

**Comment by manojTest** [comment] 2024-02-01 07:52
@chadlwilson Thank you very much. I am able to install 1.5.6 version on Circle-Ci VM machine.

**Comment by haroon-sheikh** [comment] 2024-03-16 05:38
@manojTest this should now be fixed with latest releases.

**Closed by haroon-sheikh** 2024-03-16 05:38 UTC
